(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 18,
	color: "#FFFFFF",
	manifest: [
		{src:"images/bg1.png", id:"bg1"},
		{src:"images/bg2.jpg", id:"bg2"},
		{src:"images/bg2_blur.jpg", id:"bg2_blur"}
	]
};



// symbols:



(lib.bg1 = function() {
	this.initialize(img.bg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.bg2 = function() {
	this.initialize(img.bg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,375,250);


(lib.bg2_blur = function() {
	this.initialize(img.bg2_blur);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,375,250);


(lib.t5b = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABTBfQgIgCgHgDIAEgQQAGADAHACQAHACAHAAQAOAAAHgHQAGgGAAgNIAAgMQgEAHgIADQgHADgJABQgUgBgLgOQgLgOAAgXIAAgCQAAgXALgPQALgQAUAAQAKAAAIAEQAHAEAFAIIACgOIAPAAIAABoQAAAVgLAKQgMALgWAAQgIAAgJgCgABSgYQgHAMAAAPIAAACQAAARAGAJQAIAKANAAQAJAAAGgEQAGgEADgHIAAgvQgDgHgGgDQgGgEgJAAQgOgBgGAMgAGUApQgOgPAAgXIAAgCQAAgWANgPQANgPAWAAQAVAAANAPQANAPAAAWIAAACQAAAXgNAPQgNAPgVABQgWgBgMgPgAGhgZQgIALAAAPIAAABQAAARAIALQAHALAOAAQANAAAIgLQAHgLAAgRIAAgBQAAgPgHgLQgIgLgNAAQgOAAgHALgAppAxQgGgGgBgPIAAg/IgQAAIAAgOIAQAAIAAgaIAUAAIAAAaIAUAAIAAAOIgUAAIAAA/QAAAGADAEQADACAFAAIAEAAIAEgBIACAOQgCACgFABIgIABQgLAAgIgIgAJTA3IgZhRIgBABIgYBQIgPAAIgfhoIATAAIAUBOIABAAIACgNIAVhBIAPAAIAWBBIADAOIABAAIACgOIARhBIATAAIgeBogAEiA3IAAiNIAUAAIAAB9IBDAAIAAAQgADxA3IAAhBQgBgNgGgGQgFgHgLABQgIAAgGAEQgHADgFAGIAABNIgTAAIAAiXIATAAIAAA9QAGgHAIgFQAIgEAKAAQARAAAJAKQAKAKAAAVIAABBgAALA3IAAhoIATAAIAABogAgnA3IAAg9IhFAAIAAA9IgTAAIAAiNIATAAIAABAIBFAAIAAhAIATAAIAACNgAjZA3IgigyIgNAAIAAAyIgTAAIAAiXIATAAIAABZIANAAIAcgqIAYAAIgkAwIAoA4gAlKA3IAAhBQAAgOgGgGQgFgFgLAAQgIAAgHAEQgGAEgEAGIAABMIgTAAIAAhoIARAAIABAQQAGgJAHgFQAIgEAKAAQARAAAKAKQAJAKAAAVIAABBgAm+A3IAAhoIAUAAIAABogAntA3IAAhBQAAgNgHgGQgFgHgLABQgIAAgGAEQgHADgEAGIAABNIgUAAIAAiXIAUAAIAAA9QAFgHAIgFQAIgEAKAAQARAAAJAKQAJAKAAAVIAABBgAALhMIAAgUIATAAIAAAUgAm+hMIAAgUIAUAAIAAAUg");
	this.shape.setTransform(-0.1,43.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-64.2,34.1,128.3,19.5);


(lib.t5 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHsBgIgHgBIADgSIAEAAIADAAQAGABAEgFIAGgKIAEgKIgmhmIAaAAIAUA9IADAKIAAAAIAXhHIAaAAIgsB4QgEAKgHAJQgIAHgOAAIgGgBgAkJBfQgJgCgHgEIAEgSIAOAEQAGACAIAAQANAAAGgFQAGgGAAgLIAAgLQgFAGgGAEQgIADgIgBQgTAAgMgOQgLgOAAgXIAAgCQAAgXALgPQALgQAUAAQAJAAAIAEQAGAEAFAIIADgOIAUAAIAABoQAAAUgNALQgMALgYAAQgHAAgJgCgAkHgWQgGALAAAOIAAACQAAAOAGAKQAGAIAMAAQAIAAAEgDQAGgDADgGIAAgtQgEgFgFgEQgEgDgIAAQgMAAgGAKgAEKBfIAAiQIAUAAIACANQAFgIAHgDQAIgEAJAAQATAAALAQQALAPAAAXIAAACQAAAXgLAOQgLAOgTAAQgJABgHgDQgHgEgFgGIAAAzgAEpgdQgEAEgEAFIAAAuQAEAGAEADQAGADAIAAQAMAAAGgJQAFgKAAgOIAAgCQAAgOgFgLQgHgKgMAAQgHAAgGADgAPXBSIAGggIAAgTIAYAAIAAAUIgPAfgAN9AuQgLgKAAgOIAAgBIAXAAQAAAJAGAFQAGAEAJAAQAJAAAGgDQAEgEAAgGQAAgFgEgEQgFgEgNgCQgTgEgJgHQgKgGAAgNQAAgNALgJQAMgKASAAQATAAALAKQAMAJAAAOIgBABIgXAAQAAgHgEgFQgFgEgJAAQgJAAgEADQgFAFAAAFQAAAGAFADQADADANADQAVADAJAGQAKAHAAANQAAAPgMAJQgMAJgTgBQgVABgMgLgAM+AxQgIgIABgQIAAg5IgRAAIAAgRIARAAIAAgaIAXAAIAAAaIATAAIAAARIgTAAIAAA5QAAAGADADQACADAFAAIAEAAIADgBIADARIgHADIgIAAQgOAAgHgHgALIAuQgKgLAAgXIAAg9IAYAAIAAA9QAAAOAEAFQAFAGAJAAQAJAAAFgDQAHgDACgGIAAhKIAYAAIAABoIgUAAIgCgQQgFAIgIAFQgIAEgKAAQgRABgJgLgAJWApQgNgOAAgYIAAgCQAAgWANgPQANgPAXAAQAWAAANAPQANAPAAAWIAAACQAAAYgNAOQgNAPgWAAQgXAAgNgPgAJngWQgGAJAAAOIAAACQAAAPAGAKQAGAKANAAQAMAAAGgKQAHgKgBgPIAAgCQABgOgHgJQgGgKgMAAQgNAAgGAKgAGAAwQgKgIABgQQgBgPAMgIQAMgGAXAAIASAAIAAgKQAAgIgFgFQgEgEgJAAQgJAAgFADQgEAEAAAGIgXAAIgBgBQAAgMAMgJQALgKAUAAQASAAALAKQAMAJAAARIAAAtIABANIACAMIgYAAIgCgIIgBgIQgEAHgIAFQgJAGgJgBQgRAAgIgIgAGUAMQgGAFAAAHQAAAHAEADQAEADAHABQAJgBAIgEQAHgEACgGIAAgQIgSAAQgLAAgGAFgACgAxQgIgIAAgQIAAg5IgRAAIAAgRIARAAIAAgaIAYAAIAAAaIATAAIAAARIgTAAIAAA5QAAAGACADQADADAFAAIADAAIAEgBIADARIgIADIgIAAQgOAAgGgHgAAyAuQgMgKAAgOIAAgBIAXAAQAAAJAGAFQAHAEAIAAQAJAAAGgDQAEgEAAgGQAAgFgEgEQgFgEgNgCQgSgEgKgHQgKgGAAgNQAAgNALgJQAMgKARAAQAUAAAMAKQAKAJABAOIgBABIgXAAQAAgHgEgFQgGgEgJAAQgIAAgEADQgFAFAAAFQAAAGAFADQAEADANADQAUADAJAGQAKAHgBANQAAAPgLAJQgMAJgTgBQgVABgLgLgAg0AqQgNgPAAgXIAAgEQAAgVANgPQANgPAUAAQAUAAALANQALANAAAVIAAANIhAAAIAAAAQABAMAGAIQAHAJAMAAQAKgBAFgCQAHgCAGgEIAHAPQgGAGgJADQgIADgNAAQgWABgOgPgAgigZQgFAHgCALIABAAIAoAAIAAgDQAAgJgDgGQgGgHgKAAQgIAAgHAHgAhuA3IAAg/QAAgMgFgGQgFgFgKgBQgHABgGACQgFADgEAFIAABMIgYAAIAAiXIAYAAIAAA9QAFgIAJgEQAHgEAJAAQARAAAJALQAJAKAAAWIAAA/gAlTA3IAAhoIAYAAIAABogAmFA3IAAg/QAAgMgFgGQgFgFgKgBQgHABgGACQgFADgEAFIAABMIgYAAIAAiXIAYAAIAAA9QAFgIAJgEQAHgEAJAAQARAAAJALQAJAKAAAWIAAA/gAoeA3IggguIgLAAIAAAuIgXAAIAAiXIAXAAIAABYIAKAAIAbgpIAcAAIgjAwIApA4gAqRA3IAAhBQABgLgGgFQgEgGgKAAQgIAAgFADQgGAEgDAFIAABLIgXAAIAAhoIAVAAIABAPQAGgIAIgFQAIgEAJAAQAQAAAKAKQAJAKAAAVIAABBgAsEA3IAAhoIAYAAIAABogAs2A3IAAg/QAAgMgFgGQgFgFgKgBQgHABgGACQgFADgEAFIAABMIgYAAIAAiXIAYAAIAAA9QAFgIAIgEQAIgEAJAAQARAAAJALQAKAKgBAWIAAA/gAvJA3IAAh6IgrAAIAAgTIBuAAIAAATIgrAAIAAB6gAlThLIAAgVIAYAAIAAAVgAsEhLIAAgVIAYAAIAAAVg");
	this.shape.setTransform(93.7,15.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-7.6,5.7,202.7,19.5);


(lib.t3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AE3M5QgQgJgJgPQgJgPgBgTIAAgQIAqAAIAAANQAAAMAGAIQAGAJAQAAQAOAAAGgFQAHgFABgKQACgJAAgNQAAgPgCgIQgBgIgGgEQgFgFgJgDIgegMQgRgHgKgLQgKgKgDgOQgEgOAAgRQAAgWAHgSQAIgRAQgLQAQgKAWAAQAVAAAPAJQAQAKAIAOQAJAPAAAQIAAAUIgpAAIAAgJQAAgPgHgJQgGgKgQgBQgLABgGAFQgGAFgCAIQgCAJAAAJQAAALABAHQACAHAFAEQAEAFALAEIAfANQASAGAJALQAJAKADAPQAEAPAAAVQAAAYgHASQgHATgPALQgQALgaAAQgUAAgPgJgACJNAIAAkdIB5AAIAAAmIhRAAIAABUIBHAAIAAAmIhHAAIAABUIBRAAIAAApgAA5NAIAAkdIAoAAIAAEdgAgKNAIgmh6IgZAAIAAB6IgoAAIAAkdIBCAAQAkAAAQAVQARAVAAAqQABAYgJASQgHASgSALIAqCCgAhJKiIAYAAQAOAAAHgFQAHgFACgKQACgKAAgOQAAgPgCgJQgDgKgHgFQgIgGgOAAIgWAAgAiuNAIgMg9Ig4AAIgMA9IgoAAIA/kdIAhAAIBAEdgAjrLcIApAAIgUhnIgBAAgAlgNAIg+irIgBAAIAACrIgoAAIAAkdIAnAAIA+CrIAAAAIAAirIApAAIAAEdgAoWNAIAAkdIAoAAIAAEdgArCNAIAAkdIA7AAQAbAAAQAKQAQAKAHARQAHAQAAATIAAAKQAAAPgDAKQgEAKgGAGQgGAHgJAFQAOAHAIANQAGAOAAAWIAAAQQAAAmgSAUQgTAUgnAAgAqZMXIARAAQARAAAHgGQAIgGACgLQACgLgBgOQABgOgCgKQgDgKgIgEQgHgFgPAAIgSAAgAqZKYIASAAQAUAAAHgKQAIgLgBgTQABgTgJgKQgHgKgUAAIgRAAgADdHhQgPgHgKgQQgKgPAAgXIAAiXQAAgXAKgPQAKgQAPgIQAQgHARAAQARAAAPAHQAQAIAKAQQAKAPAAAXIAAAPIgoAAIAAgPQgBgOgHgIQgJgHgLAAQgLAAgIAHQgIAIAAAOIAACXQAAAOAIAHQAIAHALAAQALAAAJgHQAHgHABgOIAAg2IghAAIAAgkIBJAAIAABaQAAAXgKAPQgKAQgQAHQgPAIgRAAQgRAAgQgIgABxHnIg/irIAAAAIAACrIgpAAIAAkdIAoAAIA9CrIABAAIAAirIAoAAIAAEdgAhDHnIAAkdIAoAAIAAEdgAjvHnIAAkdIA8AAQAjAAASAUQASATAAAjIAACFQAAAngTAUQgUATgjAAgAjHHAIATAAQARAAAIgIQAHgJAAgSIAAiJQAAgRgHgJQgHgKgSAAIgTAAgAksHnIgMg9Ig4AAIgMA9IgoAAIA/kdIAhAAIBAEdgAlpGDIApAAIgUhnIgBAAgAnWHnIglh6IgZAAIAAB6IgpAAIAAkdIBCAAQAkAAASAVQASAVAAAqQAAAYgIASQgIASgUALIAtCCgAoUFJIAXAAQAPAAAGgFQAHgFADgKQACgKAAgOQAAgPgDgJQgCgKgIgFQgHgGgOAAIgWAAgAqnHnIAAj3IgvAAIAAgmICHAAIAAAmIgwAAIAAD3gAG8CIQgPgHgLgQQgKgPABgXIAAiVQgBgXAKgPQALgQAPgIQAPgHARAAQARAAAQAHQAPAIALAQQAKAPAAAXIAACVQAAAXgKAPQgLAQgPAHQgQAIgRAAQgRAAgPgIgAHJhgQgHAIgBAOIAACVQABAOAHAHQAJAHAKAAQAMAAAIgHQAIgHAAgOIAAiVQAAgOgIgIQgIgHgMAAQgKAAgJAHgAh9CIQgPgHgKgQQgKgPAAgXIAAiVQAAgXAKgPQAKgQAPgIQAQgHARAAQARAAAQAHQAPAIAKAQQAKAPABAXIAACVQgBAXgKAPQgKAQgPAHQgQAIgRAAQgRAAgQgIgAhvhgQgIAIgBAOIAACVQABAOAIAHQAIAHALAAQALAAAIgHQAJgHgBgOIAAiVQABgOgJgIQgIgHgLAAQgLAAgIAHgAqgCIQgQgHgKgQQgKgPAAgXIAAiVQAAgXAKgPQAKgQAQgIQAPgHARAAQARAAAQAHQAPAIAKAQQAKAPABAXIAACVQgBAXgKAPQgKAQgPAHQgQAIgRAAQgRAAgPgIgAqThgQgIAIgBAOIAACVQABAOAIAHQAIAHALAAQAMAAAHgHQAJgHgBgOIAAiVQABgOgJgIQgHgHgMAAQgLAAgIAHgAKtCOIgnh6IgYAAIAAB6IgpAAIAAkbIBCAAQAkAAASAVQASAVAAAqQAAAYgIASQgIAQgUALIAsCCgAJugOIAXAAQAOAAAIgFQAGgFADgKQACgKAAgOQAAgPgCgJQgDgKgIgFQgHgGgOAAIgWAAgAEHCOIAAkbIB5AAIAAAmIhRAAIAABXIBHAAIAAAkIhHAAIAAB6gABxCOIg/ipIAAAAIAACpIgpAAIAAkbIAoAAIA9CpIABAAIAAipIAoAAIAAEbgAjuCOIAAkbIAoAAIAAEbgAlZCOIAAj1IgwAAIAAgmICIAAIAAAmIgwAAIAAD1gAoXCOIAAkbIA9AAQAQAAAOAEQAMAFAKALQALALAEAPQAEAQAAAZQAAASgCAOQgCANgIAKQgIAOgOAIQgOAHgXABIgVAAIAABvgAnvgGIAUAAQARAAAGgGQAHgGACgLQACgKgBgPQABgNgCgLQgBgLgHgHQgHgGgPgBIgWAAgACjopQgQgJgJgPQgJgPAAgTIAAgQIAoAAIAAANQAAAMAHAIQAGAJARAAQANAAAHgFQAGgFACgKQABgJAAgNQAAgPgBgIQgCgIgFgEQgGgFgKgDIgdgMQgSgHgJgLQgJgKgFgOQgDgOAAgRQAAgWAIgSQAHgRAQgLQAPgKAYAAQAUAAAQAJQAOAKAJAOQAJAPgBAQIAAAUIgoAAIAAgJQAAgPgHgJQgHgKgPgBQgLABgGAFQgGAFgCAIQgCAJAAAJQAAALABAHQABAHAFAEQAGAFAJAEIAgANQARAGAKALQAJAKAEAPQADAPgBAVQABAYgHASQgGATgQALQgPALgbAAQgUAAgPgJgAhUoiIAAkdIB4AAIAAAmIhPAAIAABUIBEAAIAAAmIhEAAIAABUIBPAAIAAApgAiXoiIgmh6IgYAAIAAB6IgqAAIAAkdIBCAAQAlAAARAVQATAVgBAqQAAAYgIASQgIASgTALIAsCCgAjVrAIAWAAQAPAAAHgFQAHgFADgKQACgKAAgOQgBgPgCgJQgDgKgHgFQgHgGgPAAIgVAAgAmSoiIAAkdIB5AAIAAAmIhRAAIAABUIBHAAIAAAmIhHAAIAABUIBRAAIAAApgAnhoiIAAh/IgzAAIAAB/IgpAAIAAkdIApAAIAAB6IAzAAIAAh6IAoAAIAAEdgAqnoiIAAj3IgvAAIAAgmICHAAIAAAmIgwAAIAAD3gAA8s/IApAAIAAApIgpAdg");
	this.shape.setTransform(74.7,94.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFC538").s().p("ACiCIQgQgHgKgQQgKgPAAgXIAAiVQAAgXAKgPQAKgQAQgIQAPgHARAAQARAAAQAHQAPAIAKAQQAKAPABAXIAACVQgBAXgKAPQgKAQgPAHQgQAIgRAAQgRAAgPgIgACvhgQgIAIAAAOIAACVQAAAOAIAHQAIAHALAAQAMAAAIgHQAIgHAAgOIAAiVQAAgOgIgIQgIgHgMAAQgLAAgIAHgAoyCIQgPgHgKgQQgKgPAAgXIAAiVQAAgXAKgPQAKgQAPgIQAQgHARAAQARAAAPAHQAQAIAKAQQAKAPAAAXIAACVQAAAXgKAPQgKAQgQAHQgPAIgRAAQgRAAgQgIgAokhgQgIAIgBAOIAACVQABAOAIAHQAIAHALAAQALAAAIgHQAIgHAAgOIAAiVQAAgOgIgIQgIgHgLAAQgLAAgIAHgAHcCOIAAkbIB6AAIAAAmIhRAAIAABUIBHAAIAAAkIhHAAIAABUIBRAAIAAApgAGRCOIg+ipIgBAAIAACpIgpAAIAAkbIAoAAIA9CpIABAAIAAipIApAAIAAEbgAg9COIAAh5Ig4iiIArAAIAhBxIABAAIAghxIAqAAIg2CiIAAB5gAj3COIAAkbIApAAIAADyIBRAAIAAApgAlCCOIg/ipIAAAAIAACpIgpAAIAAkbIAnAAIA+CpIAAAAIAAipIApAAIAAEbg");
	this.shape_1.setTransform(63.6,59.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(1.9,10.8,145.6,167);


(lib.t2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AI0KNQgPgJgJgPQgJgQgBgTIAAgPIApAAIAAANQAAALAHAJQAGAIAQABQAOAAAGgFQAGgGACgJQACgKAAgNQAAgOgCgIQgCgIgFgFQgFgEgKgEIgdgMQgSgHgJgKQgKgKgEgOQgEgOABgSQAAgWAHgRQAIgSAQgKQAPgLAXAAQAVABAPAJQAPAJAJAPQAIAOAAARIAAAUIgoAAIAAgKQAAgOgHgKQgHgKgPAAQgLAAgGAFQgGAGgCAIQgDAIAAAKQAAALACAGQABAHAFAFQAFAFAKAEIAgAMQARAHAKAKQAJAKADAPQAEAPgBAVQABAYgHATQgHATgPALQgQAKgaABQgUgBgQgIgAp6KOQgPgIgKgPQgKgQAAgXIAAiWQAAgXAKgQQAKgPAPgIQAQgIARAAQARAAAPAIQAQAIAKAPQAKAQAAAXIAACWQAAAXgKAQQgKAPgQAIQgPAIgRAAQgRAAgQgIgApsGkQgIAHgBAPIAACWQABAPAIAHQAIAHALAAQALAAAIgHQAIgHAAgPIAAiWQAAgPgIgHQgIgHgLAAQgLAAgIAHgAGGKTIAAkdIB6AAIAAAnIhRAAIAABTIBHAAIAAAnIhHAAIAABTIBRAAIAAApgADcKTIAAkdIA8AAQAjABASATQATATAAAjIAACFQAAAogUATQgTATgkAAgAEFJtIASAAQARAAAIgJQAHgJAAgSIAAiJQAAgRgHgJQgHgJgSAAIgSAAgACfKTIgMg9Ig4AAIgMA9IgoAAIA/kdIAiAAIBAEdgABiIwIApAAIgUhnIgBAAgAgIKTIgmh5IgZAAIAAB5IgpAAIAAkdIBCAAQAkAAAQAWQASAVAAApQAAAZgIARQgIASgRALIAqCCgAhHH2IAXAAQAPAAAHgGQAHgFACgKQACgJAAgPQAAgOgCgKQgDgKgHgFQgIgFgOAAIgWAAgAjaKTIAAj2IgvAAIAAgnICHAAIAAAnIgvAAIAAD2gAmKKTIg/irIAAAAIAACrIgpAAIAAkdIAnAAIA+CsIAAAAIAAisIApAAIAAEdgAhegjQgPgJgJgPQgJgQgBgTIAAgPIApAAIAAANQAAALAHAJQAGAIAQABQAOAAAGgFQAGgGACgJQACgKAAgNQAAgOgCgIQgCgIgFgFQgFgEgKgEIgdgMQgSgHgJgKQgKgKgEgOQgEgOABgSQAAgWAHgRQAIgSAQgKQAPgLAXAAQAVABAPAJQAPAJAHAPQAIAOAAARIAAAUIgmAAIAAgKQAAgOgHgKQgHgKgPAAQgLAAgGAFQgGAGgCAIQgDAIAAAKQAAALACAGQABAHAFAFQAFAFAKAEIAgAMQARAHAKAKQAHAKADAPQAEAPgBAVQABAYgHATQgFATgPALQgQAKgaABQgUgBgQgIgAkAgjQgQgJgJgPQgJgQAAgTIAAgPIApAAIAAANQAAALAGAJQAHAIAQABQANAAAHgFQAGgGACgJQABgKAAgNQAAgOgBgIQgCgIgFgFQgGgEgJgEIgegMQgRgHgKgKQgJgKgEgOQgEgOAAgSQAAgWAIgRQAHgSAQgKQAQgLAXAAQAUABAQAJQAPAJAIAPQAJAOAAARIAAAUIgpAAIAAgKQAAgOgHgKQgGgKgQAAQgLAAgGAFQgGAGgCAIQgCAIAAAKQAAALABAGQACAHAFAFQAFAFAKAEIAfAMQASAHAJAKQAJAKAEAPQADAPAAAVQAAAYgHATQgGATgQALQgPAKgbABQgUgBgPgIgAEdgdIAAkdIB6AAIAAAnIhRAAIAABTIBHAAIAAAnIhHAAIAABTIBRAAIAAApgACngdIg6kdIArAAIAgDHIABAAIAhjHIArAAIg7EdgAAqgdIAAkdIApAAIAAEdgAlXgdIgMg9Ig4AAIgMA9IgoAAIA/kdIAiAAIBAEdgAmUiAIApAAIgUhnIgBAAgAoMgdIAAitIgBAAIgoB6IgUAAIgph6IAAAAIAACtIgpAAIAAkdIAnAAIA0CXIABAAIA0iXIAoAAIAAEdgAigl8QgPgJgJgPQgJgQgBgTIAAgPIApAAIAAANQAAALAHAJQAGAIAQABQAOAAAGgFQAGgGACgJQACgKAAgNQAAgOgCgIQgCgIgFgFQgFgEgKgEIgdgMQgSgHgJgKQgKgKgEgOQgEgOABgSQAAgWAHgRQAIgSAQgKQAPgLAXAAQAVABAPAJQAPAJAJAPQAIAOAAARIAAAUIgoAAIAAgKQAAgOgHgKQgHgKgPAAQgLAAgGAFQgGAGgCAIQgDAIAAAKQAAALACAGQABAHAFAFQAFAFAKAEIAgAMQARAHAKAKQAJAKADAPQAEAPgBAVQABAYgHATQgHATgPALQgQAKgaABQgUgBgQgIgAlDl8QgPgJgJgPQgJgPAAgTIAAjdIApAAIAADZQAAAPAHAIQAHAHALAAQALAAAHgHQAHgIAAgPIAAjZIApAAIAADdQAAATgJAPQgJAPgPAJQgPAIgSABQgSgBgPgIgACXl2IgMg9Ig3AAIgMA9IgpAAIBAkdIAhAAIBAEdgABbnZIApAAIgUhnIgBAAgAn4l2IAAkdIApAAIAAD0IBRAAIAAApgAqbl2IAAkdIA9AAQARAAANAFQAMAEALAMQAKAKAEAQQAFAPgBAZQABATgDANQgCAOgHALQgJAOgOAIQgOAIgXAAIgUAAIAABvgApyoLIATAAQARAAAHgGQAHgGABgLQACgLAAgOQAAgOgBgLQgCgLgHgGQgGgHgQAAIgVAAg");
	this.shape.setTransform(70.8,77);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFC538").s().p("AFfCHQgPgJgJgPQgIgPgBgSIAAjbIApAAIAADXQAAAPAHAHQAHAHALAAQALAAAHgHQAHgHABgPIAAjXIAoAAIAADbQAAASgJAPQgIAPgPAJQgPAJgTAAQgSAAgPgJgAkfCIQgJgJgBgNIAAgaQABgPAJgJQAJgJAQAAQAPAAAJAJQAJAJABAPIAAAaQgBANgJAJQgJAIgPAAQgQAAgJgIgAkNBSQgDADgBAEIAAAVQABAEADADQACADAFAAQADAAADgDQADgDABgEIAAgVQgBgEgDgDQgDgDgDAAQgFAAgCADgAnWCJQgOgIgIgNQgJgOAAgTIAAilQAAgTAJgOQAIgOAOgHQANgHARAAQAQAAAOAHQANAHAJAOQAIAOAAATIAAClQAAATgIAOQgJANgNAIQgOAHgQAAQgRAAgNgHgAnHhhQgFAGAAAJIAAClQAAAJAFAFQAGAGAJAAQAIAAAGgGQAFgFABgJIAAilQgBgJgFgGQgGgFgIgBQgJABgGAFgAprCJQgOgIgIgNQgJgOAAgTIAAilQAAgTAJgOQAIgOAOgHQANgHARAAQAQAAAOAHQANAHAJAOQAIAOAAATIAAClQAAATgIAOQgJANgNAIQgOAHgQAAQgRAAgNgHgApchhQgFAGAAAJIAAClQAAAJAFAFQAGAGAJAAQAIAAAGgGQAFgFABgJIAAilQgBgJgFgGQgGgFgIgBQgJABgGAFgAL6COIg/ipIAAAAIAACpIgpAAIAAkbIAnAAIA+CpIAAAAIAAipIApAAIAAEbgAJQCOIgmh6IgYAAIAAB6IgpAAIAAkbIBCAAQAkAAASAVQASAVAAAqQAAAYgIASQgIAQgUALIAsCCgAISgOIAXAAQAOAAAHgFQAHgFADgKQACgKAAgOQAAgPgDgJQgCgKgIgFQgHgGgPAAIgVAAgADUCOIAAj1IgvAAIAAgmICHAAIAAAmIgvAAIAAD1gAAlCOIAAkbIB6AAIAAAmIhRAAIAABUIBHAAIAAAkIhHAAIAABUIBRAAIAAApgAgcCOIgmh6IgYAAIAAB6IgpAAIAAkbIBCAAQAkAAASAVQAQAVAAAqQAAAYgGASQgIAQgUALIAqCCgAhagOIAXAAQAOAAAHgFQAHgFADgKQACgKAAgOQAAgPgDgJQgCgKgIgFQgHgGgPAAIgVAAgAllCOIBhkbIAbAAIhiEbgAsfCOIAAgnIBJiIQAGgLABgIIABgTIgBgPQgBgHgEgFQgFgEgJgBQgKAAgFAGQgFAFAAAKIAAAXIgpAAIAAgWQAAgSAIgNQAIgPAOgIQAOgIARAAQAVAAANAKQAOAKAGAQQAGAQAAATIAAAWQgBAJgDAIQgDAJgGALIg8ByIBJAAIAAApgAlhg/QgJgIAAgOIAAgaQAAgPAJgIQAJgJAQAAQAQAAAJAJQAJAIAAAPIAAAaQAAAOgJAIQgJAJgQAAQgQAAgJgJgAlPh0QgDADAAAEIAAAUQAAAFADADQADACAEABQAEgBADgCQADgDAAgFIAAgUQAAgEgDgDQgDgDgEAAQgEAAgDADg");
	this.shape_1.setTransform(83.4,94.3);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(3.4,10.8,160.2,132.5);


(lib.t1 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIaE0QgPgJgJgPQgJgQgBgTIAAgPIApAAIAAANQAAALAHAJQAGAIAQABQAOAAAGgFQAGgGACgJQACgKAAgNQAAgOgCgIQgCgIgFgFQgFgEgKgEIgdgMQgSgHgJgKQgKgKgEgOQgEgOABgSQAAgWAHgRQAIgSAQgKQAPgLAXAAQAVABAPAJQAPAJAJAPQAIAOAAARIAAAUIgoAAIAAgKQAAgOgHgKQgHgKgPAAQgLAAgGAFQgGAGgCAIQgDAIAAAKQAAALACAGQABAHAFAFQAFAFAKAEIAgAMQARAHAKAKQAJAKADAPQAEAPgBAVQABAYgHATQgHATgPALQgQAKgaABQgUgBgQgIgABfE0QgQgJgJgPQgJgQAAgTIAAgPIApAAIAAANQAAALAGAJQAHAIAQABQANAAAHgFQAGgGACgJQABgKAAgNQAAgOgBgIQgCgIgFgFQgGgEgJgEIgegMQgRgHgKgKQgJgKgEgOQgEgOAAgSQAAgWAIgRQAHgSAQgKQAQgLAXAAQAUABAQAJQAPAJAIAPQAJAOAAARIAAAUIgpAAIAAgKQAAgOgHgKQgGgKgQAAQgLAAgGAFQgGAGgCAIQgCAIAAAKQAAALABAGQACAHAFAFQAFAFAKAEIAfAMQASAHAJAKQAJAKAEAPQADAPAAAVQAAAYgHATQgGATgQALQgPAKgbABQgUgBgPgIgAhCE0QgPgJgJgPQgJgQgBgTIAAgPIApAAIAAANQAAALAHAJQAGAIAQABQAOAAAGgFQAGgGACgJQACgKAAgNQAAgOgCgIQgCgIgFgFQgFgEgKgEIgdgMQgSgHgJgKQgKgKgEgOQgEgOABgSQAAgWAHgRQAIgSAQgKQAPgLAXAAQAVABANAJQAPAJAJAPQAIAOAAARIAAAUIgmAAIAAgKQAAgOgHgKQgHgKgPAAQgLAAgGAFQgGAGgCAIQgDAIAAAKQAAALACAGQABAHAFAFQAFAFAKAEIAgAMQAPAHAKAKQAJAKADAPQAEAPgBAVQABAYgHATQgHATgPALQgOAKgaABQgUgBgQgIgAGWE6IAAj2IgvAAIAAgnICHAAIAAAnIgvAAIAAD2gADnE6IAAkdIB6AAIAAAnIhRAAIAABTIBHAAIAAAnIhHAAIAABTIBRAAIAAApgAiZE6IgMg9Ig3AAIgMA9IgpAAIBAkdIAhAAIBAEdgAjVDXIApAAIgUhnIgBAAgAn0E6IAAkdIA9AAQAjABASATQASATAAAjIAACFQAAAogTATQgUATgkAAgAnLEUIATAAQARAAAHgJQAIgJAAgSIAAiJQAAgRgHgJQgHgJgSAAIgTAAgAo/E6Ig+irIgBAAIAACrIgpAAIAAkdIAoAAIA9CsIABAAIAAisIApAAIAAEdgAriE6IgMg9Ig4AAIgMA9IgoAAIA/kdIAiAAIBAEdgAsfDXIApAAIgUhnIgBAAgALxgjQgPgJgJgPQgJgQgBgTIAAgPIApAAIAAANQAAALAHAJQAGAIAQABQAOAAAGgFQAGgGACgJQACgKAAgNQAAgOgCgIQgCgIgFgFQgFgEgKgEIgdgMQgSgHgJgKQgKgKgEgOQgEgOABgSQAAgWAHgRQAIgSAQgKQAPgLAXAAQAVABAPAJQAPAJAJAPQAIAOAAARIAAAUIgoAAIAAgKQAAgOgHgKQgHgKgPAAQgLAAgGAFQgGAGgCAIQgDAIAAAKQAAALACAGQABAHAFAFQAFAFAKAEIAgAMQARAHAKAKQAJAKADAPQAEAPgBAVQABAYgHATQgHATgPALQgQAKgaABQgUgBgQgIgAkDgiQgPgIgKgPQgKgQAAgXIAAiWQAAgXAKgQQAKgPAPgIQAQgIARAAQARAAAPAIQAQAIAKAPQAKAQAAAXIAACWQAAAXgKAQQgKAPgQAIQgPAIgRAAQgRAAgQgIgAj1kMQgIAHgBAPIAACWQABAPAIAHQAIAHALAAQALAAAIgHQAIgHAAgPIAAiWQAAgPgIgHQgIgHgLAAQgLAAgIAHgAsngiQgPgIgKgPQgKgQAAgXIAAiWQAAgXAKgQQAKgPAPgIQAQgIARAAQARAAAPAIQAQAIAKAPQAKAQAAAXIAACWQAAAXgKAQQgKAPgQAIQgPAIgRAAQgRAAgQgIgAsZkMQgIAHgBAPIAACWQABAPAIAHQAIAHALAAQALAAAIgHQAIgHAAgPIAAiWQAAgPgIgHQgIgHgLAAQgLAAgIAHgAJDgdIAAkdIB6AAIAAAnIhRAAIAABTIBHAAIAAAnIhHAAIAABTIBRAAIAAApgAGggdIAAkdIA+AAQAQAAANAFQANAEAKAMQALAKAEAQQAEAPAAAZQAAATgCANQgDAOgHALQgIAOgOAIQgPAIgWAAIgVAAIAABvgAHJiyIAUAAQAQAAAHgGQAHgGACgLQACgLgBgOQABgOgCgLQgBgLgHgGQgHgHgQAAIgVAAgAErgdIAAh4Ig4ilIAsAAIAgByIABAAIAhhyIArAAIg4ClIAAB4gACbgdIAAj2IgvAAIAAgnICHAAIAAAnIgvAAIAAD2gAgTgdIg/irIAAAAIAACrIgpAAIAAkdIAnAAIA+CsIAAAAIAAisIAnAAIAAEdgAl0gdIAAkdIAoAAIAAEdgAnggdIAAj2IgvAAIAAgnICHAAIAAAnIgvAAIAAD2gAqegdIAAkdIA+AAQAQAAANAFQANAEAKAMQALAKAEAQQAEAPAAAZQAAATgCANQgDAOgHALQgIAOgOAIQgPAIgWAAIgVAAIAABvgAp1iyIAUAAQAQAAAHgGQAHgGACgLQACgLgBgOQABgOgCgLQgBgLgHgGQgHgHgQAAIgVAAg");
	this.shape.setTransform(88.1,111.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFC538").s().p("AJUE1QgPgIgKgPQgKgQAAgXIAAiWQAAgXAKgQQAKgPAPgIQAQgIARAAQARAAAPAIQAQAIAKAPQAKAQAAAXIAACWQAAAXgKAQQgKAPgQAIQgPAIgRAAQgRAAgQgIgAJiBLQgIAHgBAPIAACWQABAPAIAHQAIAHALAAQALAAAIgHQAIgHAAgPIAAiWQAAgPgIgHQgIgHgLAAQgLAAgIAHgACuE1QgQgIgKgPQgKgQAAgXIAAiWQAAgXAKgQQAKgPAQgIQAPgIARAAQARAAAQAIQAPAIAKAPQAKAQABAXIAACWQgBAXgKAQQgKAPgPAIQgQAIgRAAQgRAAgPgIgAC7BLQgIAHAAAPIAACWQAAAPAIAHQAIAHALAAQAMAAAIgHQAIgHAAgPIAAiWQAAgPgIgHQgIgHgMAAQgLAAgIAHgAjKE3QgPgGgKgPQgKgPAAgaIAAicQAAgTAIgPQAIgOAPgJQAPgJAUAAQATAAAPAJQAOAJAJAPQAIAPABAUIAAAQIgpAAIAAgOQAAgMgHgIQgHgJgLAAQgPAAgGAJQgFAKAAAOIAACSQAAAMAGAIQAGAJANAAQAGAAAGgDQAGgCAEgHQAEgGAAgLIAAgOIApAAIAAASQgBARgIAPQgJAPgOAJQgPAJgSABQgQAAgQgGgAswE0QgPgJgJgPQgJgQgBgTIAAgPIApAAIAAANQAAALAHAJQAGAIAQABQAOAAAGgFQAGgGACgJQACgKAAgNQAAgOgCgIQgCgIgFgFQgFgEgKgEIgdgMQgSgHgJgKQgKgKgEgOQgEgOABgSQAAgWAHgRQAIgSAQgKQAPgLAXAAQAVABAPAJQAPAJAJAPQAIAOAAARIAAAUIgoAAIAAgKQAAgOgHgKQgHgKgPAAQgLAAgGAFQgGAGgCAIQgDAIAAAKQAAALACAGQABAHAFAFQAFAFAKAEIAgAMQARAHAKAKQAJAKADAPQAEAPgBAVQABAYgHATQgHATgPALQgQAKgaABQgUgBgQgIgALdE6IAAkdIB6AAIAAAnIhRAAIAABWIBHAAIAAAnIhHAAIAAB5gAGdE6Ig+irIgBAAIAACrIgpAAIAAkdIAoAAIA9CsIABAAIAAisIApAAIAAEdgAA8E6IAAkdIApAAIAAEdgAgtE6IAAj2IgwAAIAAgnICGAAIAAAnIguAAIAAD2gAl/E6IAAkdIB6AAIAAAnIhRAAIAABTIBGAAIAAAnIhGAAIAABTIBRAAIAAApgAoTE6IAAkdIApAAIAAD0IBRAAIAAApgAqnE6IAAkdIB6AAIAAAnIhRAAIAABTIBGAAIAAAnIhGAAIAABTIBRAAIAAApgAHQgiQgPgIgKgPQgKgQAAgXIAAiWQAAgXAKgQQAKgPAPgIQAQgIARAAQARAAAPAIQAQAIAKAPQAKAQAAAXIAAAOIgpAAIAAgOQAAgPgIgHQgIgHgLAAQgLAAgIAHQgIAHgBAPIAACWQABAPAIAHQAIAHALAAQALAAAIgHQAIgHAAgPIAAg2IggAAIAAgkIBJAAIAABaQAAAXgKAQQgKAPgQAIQgPAIgRAAQgRAAgQgIgAElgjQgPgJgJgPQgIgPgBgTIAAjdIApAAIAADZQAAAPAHAIQAHAHALAAQALAAAHgHQAHgIABgPIAAjZIAoAAIAADdQAAATgJAPQgIAPgPAJQgPAIgTABQgSgBgPgIgAJZgdIAAkdIB6AAIAAAnIhRAAIAABTIBHAAIAAAnIhHAAIAABTIBRAAIAAApgAC1gdIAAh/IgyAAIAAB/IgpAAIAAkdIApAAIAAB7IAyAAIAAh7IApAAIAAEdgAgsgdIgMg9Ig3AAIgMA9IgpAAIBAkdIAhAAIBAEdgAhoiAIApAAIgUhnIgBAAgAkrgdIAAh/IgzAAIAAB/IgpAAIAAkdIApAAIAAB7IAzAAIAAh7IAoAAIAAEdgAnxgdIAAj2IgvAAIAAgnICHAAIAAAnIgvAAIAAD2gApcgdIAAkdIApAAIAAEdgArHgdIgfi5IgBAAIgeC5IgnAAIgqkdIArAAIAUC1IABAAIAgi1IAfAAIAhC6IABAAIAUi6IArAAIgqEdg");
	this.shape_1.setTransform(88.2,42.5);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(2.1,10.8,172,132.5);


(lib.strip = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFC538").s().p("AgdTiMAAAgnDIA7AAMAAAAnDg");
	this.shape.setTransform(3,125);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,6,250);


(lib.logo_mc = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2F2E2E").s().p("AAVA8QgjAAgIgCQgPgDgGgHQgGgIgCgNQgBgFAAgUQAAgVABgGQADgPAHgIQAJgIAZgCIAjgBQAoAAALADQARADAEANQADAHAAAPIgkAAQAAgEgCgFQgEgEgJAAIgzAAIgFABQgGACgDAFQgCAFAAAVQAAAPACAEQACAIAJABIAWABIAiAAQAMgBABgJIAAgIIguAAIAAgUIBSAAIAAAPQAAAZgDAHQgDAJgGAFQgJAEgOABgADrA7IAAguIhTAAIAAAuIglAAIAAh1IAlAAIAAAsIBTAAIAAgsIAlAAIAAB1gAhkA7IAAh1IAlAAIAAB1gAiWA7IAAguIhUAAIAAAuIgmAAIAAh1IAmAAIAAAsIBUAAIAAgsIAlAAIAAB1g");
	this.shape.setTransform(31.8,15.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FEFEFE").s().p("AheA6QgOgCgGgIQgHgFgCgOQgCgIAAgVIABgUQgBgFADgHQADgMAJgHQAKgGAXgCIAhAAQAqAAAKABQAPADAGAIQAHAJABAMQACAKAAARQAAAbgFAKQgEAKgJAFQgIAEgFABIgVACIgdAAQgqAAgKgCgAhHgdQgLABgDAHQgCAFAAAQQAAAQACAGQADAGAMACQAHABAUAAQAbAAAHgCQAHgBACgFQACgFgBgIIABgKQAAgQgCgGQAAgEgDgBQgFgDgHAAIgbAAQgZAAgEABgAkSA7IAAh1IAlAAIAABXIBkAAIAAAegACyA7IgVhJIgXBJIgzAAIgsh2IAoAAIAdBRIAahRIAuAAIAZBRIAdhRIAoAAIgtB2g");
	this.shape_1.setTransform(97.6,21.9);

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E1E0DF").s().p("AAABlIk8A5IAAkCIE8g5IE9A5IAAECg");
	this.shape_2.setTransform(31.8,15.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B6B6A").s().p("Ak8BlIAAkCIE8A5IE9g5IAAECIk9A5g");
	this.shape_3.setTransform(97.2,21.8);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,129,37.7);


(lib.btnbg = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F0F0F0").s().p("A0TDvIAAneMAonAAAIAAHeg");
	this.shape.setTransform(130,24);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FCCD2A").s().p("A0TAPIAAgdMAonAAAIAAAdg");
	this.shape_1.setTransform(130,49.5);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,260,51);


(lib.bg2b = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bg2_blur();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,375,250);


(lib.bg2a = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bg2();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,375,250);


(lib.bg1_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bg1();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib._bg = function() {
	this.initialize();

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A3bTiMAAAgnDMAu2AAAMAAAAnDg");
	this.shape.setTransform(150,125);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib._clicktag = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#424242").s().p("A3bTiMAAAgnDMAu2AAAMAAAAnDg");
	this.shape.setTransform(150,125);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{on:1,off:7});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_6 = function() {
		this.stop();
	}
	this.frame_12 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(6).call(this.frame_6).wait(6).call(this.frame_12).wait(1));

	// t
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AQZAhQgNgOAAgTQAAgSANgOQAPgNATAAQAVAAAOANQANAOAAASQAAATgNAOQgOANgVAAQgTAAgPgNgAQlgWQgKAKAAAMQAAANAKAKQAJAKANAAQAOAAAKgKQAIgKABgNQgBgMgIgKQgKgKgOAAQgNAAgJAKgAlKAhQgOgOAAgTQAAgSAOgOQAOgNATAAQAVAAANANQAOAOABASQgBATgOAOQgNANgVAAQgTAAgOgNgAk/gWQgJAKAAAMQAAANAJAKQAJAKANAAQAOAAAJgKQAKgKgBgNQABgMgKgKQgJgKgOAAQgNAAgJAKgAqgAkQgLgLABgTIAAgyIAPAAIAAAxQAAAMAGAIQAHAHAKAAQALAAAGgHQAGgIAAgMIAAgxIAPAAIAAAyQABATgLALQgLAKgRAAQgRAAgLgKgAvNAhQgNgNAAgUQAAgSANgOQAOgNAUAAQAUAAANALIgIALQgGgEgFgBQgGgCgHgBQgNABgKAIQgKAJABANQgBAOAKAJQAJAJANAAQANAAAIgGIAAgZIAQAAIAAAgQgNAOgYgBQgUAAgOgNgAxqAgIAKgMQANAMAPAAQAHAAAEgDQAFgDAAgGQAAgEgEgEQgEgCgKgDIgQgFIgJgCQgHgHgBgMQABgNAIgHQAKgGANAAQAJAAAJACQAIADAGAGIgIALQgEgDgHgDQgHgDgGAAQgHAAgFAEQgEACAAAGQAAAFAEADQAFADAOADQAOADAHAFQAHAGAAAMQAAALgJAIQgJAHgPAAQgVAAgQgOgAPfAtIAAhFIggA9IgJAAIgfg9IAABFIgQAAIAAhZIAZAAIAbA3IAcg3IAXAAIAABZgAMoAtIAAhZIBBAAIAAAPIgxAAIAAAYIArAAIAAAMIgrAAIAAAYIAyAAIAAAOgAK5AtIAAhZIAgAAQAXAAAOAMQANAMAAAUQAAAVgMAMQgOAMgaAAgALJAfIARAAQAQAAAJgIQAJgHgBgQQABgdgkAAIgPAAgAIsAtIAAhZIBBAAIAAAPIgxAAIAAAYIAsAAIAAAMIgsAAIAAAYIAyAAIAAAOgAHOAtIAAhZIBAAAIAAAPIgxAAIAAAYIArAAIAAAMIgrAAIAAAYIAyAAIAAAOgAGfAtIgXgeIgTAAIAAAeIgQAAIAAhZIAiAAQAVAAAIAIQAJAGAAAQQAAAUgTAGIAYAhgAF1ABIASAAQANAAAFgCQAFgEAAgJQAAgJgFgDQgFgDgMAAIgTAAgAEMAtIAAhZIA9AAIAAAPIgtAAIAAAZIAoAAIAAAMIgoAAIAAAlgACAAtIAAhZIBAAAIAAAPIgwAAIAAAYIArAAIAAAMIgrAAIAAAYIAxAAIAAAOgABNAtIAAgkIgtAAIAAAkIgPAAIAAhZIAPAAIAAAoIAtAAIAAgoIAQAAIAABZgAgyAtIAAhKIgcAAIAAgPIBHAAIAAAPIgcAAIAABKgAiiAtIgWgeIgUAAIAAAeIgQAAIAAhZIAjAAQAUAAAJAIQAJAGAAAQQAAAUgTAGIAYAhgAjMABIATAAQANAAAFgCQAEgEAAgJQAAgJgEgDQgFgDgMAAIgUAAgAmrAtIAAhZIA9AAIAAAPIgtAAIAAAZIAnAAIAAAMIgnAAIAAAlgAo7AtIAAhZIAfAAQAVAAAJAJQAKAHAAARQAAAOgKAIQgKAIgUAAIgQAAIAAAagAosAFIASAAQANAAAEgFQAEgDAAgJQAAgKgFgDQgGgEgNAAIgPAAgAslAtIg0hAIAABAIgPAAIAAhZIAPAAIA1BDIAAhDIAQAAIAABZgAwHAtIAAhZIAQAAIAABZgAr1AOIAAgOIArAAIAAAOg");
	this.shape.setTransform(-0.8,25.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(13));

	// Layer 4
	this.instance = new lib.btnbg();
	this.instance.setTransform(0,25.5,1,1,0,0,0,130,25.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},6).to({alpha:0},6).wait(1));

	// Layer 3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FC9E09").s().p("A0SAPIAAgdMAolAAAIAAAdg");
	this.shape_1.setTransform(0,49.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(13));

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FCCD2A").s().p("A0SDvIAAneMAolAAAIAAHeg");
	this.shape_2.setTransform(0,24);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(13));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-130,0,260,51);


(lib.bg2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_27 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(27).call(this.frame_27).wait(1));

	// Layer 2
	this.instance = new lib.bg2b();
	this.instance.setTransform(187.5,125,1,1,0,0,0,187.5,125);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(16).to({_off:false},0).to({alpha:1},11).wait(1));

	// Layer 1
	this.instance_1 = new lib.bg2a();
	this.instance_1.setTransform(187.5,125,1,1,0,0,0,187.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(28));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,375,250);


// stage content:
(lib.HighLow_300x250_4b = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		stage.enableMouseOver(20);
		
		this.loopNumber = 0 ;
		
		// CLICKTHROUGH
		this.clickTagBtn.addEventListener("click", function () {
			console.log("clickthrough");
			window.open(window.clickTAG);
		});
		
		// CTA
		this.clickTagBtn.addEventListener("mouseover", function () {
			exportRoot.bt.gotoAndPlay("on");
		});
		
		this.clickTagBtn.addEventListener("mouseout", function () {
			exportRoot.bt.gotoAndPlay("off");
		});
	}
	this.frame_243 = function() {
		if(this.loopNumber >= 1){
			console.log("STOP BANNER");
			this.stop();
		} else {
			this.loopNumber++;
			console.log("RESTART: " + this.loopNumber);
		}
	}
	this.frame_251 = function() {
		this.gotoAndPlay(1);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(243).call(this.frame_243).wait(8).call(this.frame_251).wait(1));

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A3bTiMAAAgnDMAu2AAAMAAAAnDgA3RTYMAuiAAAMAAAgmvMguiAAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(252));

	// clickTagBtn
	this.clickTagBtn = new lib._clicktag();
	new cjs.ButtonHelper(this.clickTagBtn, 0, 1, 2, false, new lib._clicktag(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickTagBtn).wait(252));

	// btn
	this.bt = new lib.btn();
	this.bt.setTransform(150,261);
	this.bt.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.bt).wait(191).to({y:181},0).to({alpha:1},7).wait(46).to({y:331},7,cjs.Ease.get(0.9)).wait(1));

	// t5
	this.instance = new lib.t5b();
	this.instance.setTransform(149.3,123.4,1,1,0,0,0,0,28.4);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(158).to({_off:false},0).to({alpha:1},7).wait(79).to({y:-96.6},7,cjs.Ease.get(0.9)).wait(1));

	// t5
	this.instance_1 = new lib.t5();
	this.instance_1.setTransform(150.2,122.1,1,1,0,0,0,95,25.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(153).to({_off:false},0).to({alpha:1},7).wait(84).to({y:-97.9},7,cjs.Ease.get(0.9)).wait(1));

	// logo
	this.instance_2 = new lib.logo_mc();
	this.instance_2.setTransform(148.5,57.8,1,1,0,0,0,64.5,18.8);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(191).to({_off:false},0).to({alpha:1},7).wait(46).to({y:-162.2},7,cjs.Ease.get(0.9)).wait(1));

	// strip
	this.instance_3 = new lib.strip();
	this.instance_3.setTransform(-5,125,1,1,0,0,0,3,125);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(4).to({_off:false},0).to({x:3},5,cjs.Ease.get(0.9)).wait(122).to({x:153},4,cjs.Ease.get(-1)).to({x:303},4,cjs.Ease.get(1)).to({_off:true},1).wait(104).to({_off:false},0).to({x:-3},7,cjs.Ease.get(0.9)).wait(1));

	// t3
	this.instance_4 = new lib.t3();
	this.instance_4.setTransform(-149.2,125.8,1,1,0,0,0,78.8,94.8);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(85).to({_off:false},0).to({x:120.8},7,cjs.Ease.get(1)).wait(39).to({x:270.8},4,cjs.Ease.get(-1)).to({x:420.8},4,cjs.Ease.get(1)).to({_off:true},1).wait(112));

	// t2
	this.instance_5 = new lib.t2();
	this.instance_5.setTransform(-120.5,124.5,1,1,0,0,0,87.5,77.5);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(39).to({_off:false},0).to({x:129.5},7,cjs.Ease.get(1)).wait(37).to({x:429.5},7,cjs.Ease.get(-1)).to({_off:true},1).wait(161));

	// t1
	this.instance_6 = new lib.t1();
	this.instance_6.setTransform(-145.6,124.5,1,1,0,0,0,92.4,77.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({x:134.4},7,cjs.Ease.get(1)).wait(30).to({x:484.4},7,cjs.Ease.get(-1)).to({_off:true},1).wait(207));

	// bg1
	this.instance_7 = new lib.bg1_1();
	this.instance_7.setTransform(150.5,125,1,1,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(131).to({x:300.5},4,cjs.Ease.get(-1)).to({x:450.5},4,cjs.Ease.get(1)).to({_off:true},1).wait(104).to({_off:false,x:455.5},0).to({x:150},7,cjs.Ease.get(0.9)).wait(1));

	// Layer 26
	this.instance_8 = new lib.bg2_1();
	this.instance_8.setTransform(-112.5,125,1,1,0,0,0,187.5,125);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(131).to({_off:false},0).to({x:37.5},4,cjs.Ease.get(-1)).to({x:187.5},4,cjs.Ease.get(1)).to({x:112.5},105).to({x:-187.5},7,cjs.Ease.get(0.9)).wait(1));

	// bg
	this.instance_9 = new lib._bg();
	this.instance_9.setTransform(150,125,1,1,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(252));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-85.9,125,536.4,312);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;