(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 18,
	color: "#33FF00",
	manifest: [
		{src:"images/bg1.png", id:"bg1"},
		{src:"images/bg2.jpg", id:"bg2"},
		{src:"images/bg2_blur.jpg", id:"bg2_blur"}
	]
};



// symbols:



(lib.bg1 = function() {
	this.initialize(img.bg1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.bg2 = function() {
	this.initialize(img.bg2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,375,250);


(lib.bg2_blur = function() {
	this.initialize(img.bg2_blur);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,375,250);


(lib.t5b = function() {
	this.initialize();

	// Layer 2 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABHBhQgJgCgHgDIAAgQQAJAGAIADQAJACAJAAQAGAAAGgCQAGgCAEgEQADgDACgHQACgGAAgJIAAgNQgHAMgJAFQgIAHgLAAQgFgBgGgCQgFgCgEgGQgEgFgDgIQgCgHAAgKQAAgYAOgNQAGgIAIgDQAJgEAKAAIAgABIgBBXQgBALgCAGQgCAGgDADQgEAFgFACQgFADgIACQgHACgHAAQgKAAgIgDgABbgNQgGADgEAFQgKAIABAUIAAANQACAEADADQAEAIAHgBQAIABAHgIQAIgGAIgOIAAgkQgIgCgHAAQgHAAgGACgAkgBIQAAgEgEgJQAUABAOgCQAPgBAKgDQAIgDAIgEQAGgEAEgFIAEgJQACgEAAgEQAAgFgCgFQgCgFgDgDQgIgGgQAAQgJAAgIACIgTAFQgQAJgQATIgPgGIALhTIAVAHIgJAdQgDANAAAMQANgGAXgLIAOgEIAPgBQAMAAAIADQAJADAHAFQAGAGADAFQADAHABAJQgBALgFAKQgEAJgKAIQgNAJgVAGQgXAEgeABgAnPBLQgHgDgGgGQgGgDgCgEQgDgFAAgFQAAgFADgFQACgFAGgEQADgEAHgCQAIgCAKAAQAJAAALADIgCghIABgUIAUACQgCAMAAAMIABAgIAPAEIAFADIAIAEIAQAIIgKATQgZgQgJgEQgBAIgBAFQgCAGgEACQgEAEgIACQgHACgJAAQgJAAgIgCgAnQAoQgGAFABADIACAHQABACAGACQAGADAGAAQAGAAAEgCQAEgBAEgCQACgCAAgFQABgDgBgGQgMgFgLAAQgHAAgGAEgAF6A9QgHgDgGgHQgGgGgEgJQgDgJAAgLQAAgKADgIQAEgIAGgGQAGgHAHgEQAIgDAKAAQAJAAAIADQAHAEAHAHQAMAMAAAUQAAALgEAJQgDAIgFAHQgHAHgHADQgIADgJABQgKgBgIgDgAGBgOQgEACgEAEQgEAEgCAFQgCAHAAAIQAAAJACAHQACAGAEAEQAHAKAMAAQAFAAAFgDQAFgCAEgFQAHgIAAgSQAAgIgBgHQgCgFgEgEIgJgGQgFgCgFAAQgGAAgFACgAIDA+IgUhFIgBAAIgRBFIgPAAIgPhZIAOAAIALBDIAQhDIAPAAIAQA1IADAOIAKhDIAMAAIgPBZgAEHA+IAAh9IARAAIAABvIA0AAIAAAOgADbA+IgBhAQgBgGgCgDQgDgFgGABQgKgBgIAHQgIAGgHAMIAAA1IgPAAIAAiBIAPAAIAAA8QAHgLAJgGQAIgFAKgBQAHAAAEACQAFACAEAFQADAEACAIQACAJAAALIAAAzgAgOA+IAAhMIgaAAIAAgNIAoAAIAABMIAZAAIAAANgAhPA+IAAg7IgvAAIAAA7IgQAAIAAh9IAQAAIAAA3IAvAAIAAg3IARAAIAAB9gAofAyQANgYAKgXQAMgVAHgWIgeAAIAAgSIAWABIAOgBQAHgWADgMIAUAFIgKAbIAcgGIABASIgjAGIgVA3QgOAdgKARgAmWglIgfgIIAEgQQAVADAMAEIAfALIgHASQgRgIgNgEgAgOg1QgDgCABgEQgBgFADgDQADgCAEAAQAFAAACACQABADAAAFQAAAEgBACQgEADgDABQgEgBgDgDgAkFhFIgfgNIAIgRQATAJAIADIAkAKIgFASQgVgFgOgFg");
	this.shape.setTransform(0,43.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-64.2,30.9,226.7,98);


(lib.t5 = function() {
	this.initialize();

	// Layer 2 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Am/BJIANAAIADgBIABgCIAAg2Ih8AAIAABKIgSAAIAAhaIChAAIAABIQAAAFgBAEQgBAEgDABQgEACgWAEQgCgKgDgJgAq0BKQAIgCALgGIARgLQgMgPgBgEIgGgSIgNAAIAAgPIBDAAIACgCIANAMIgQAdQgHAKgEADQAHAGAJAFIASAIIgEAGIgHAKIgTgKIgRgNQgRAQgUAHQgDgHgGgJgAqNAfQADAHAFAGQAEgEAMgWIgcAAQABAHADAGgArHBaIAAgWIhCAMIgDgSIARgCIAAhEIgRAAIAAgOICyAAIAAAOIhdAAIAABigArqA7IAjgFIAAgMIgjAAgArqAdIAjAAIAAgMIgjAAgArqAEIAjAAIAAgMIgjAAgAKiBYIAAirIAWAAIAAA3QAjAMALAGIAnASIgLATQgTgMgTgJQgVgIgPgFIAABfgAHMBFQASgFAVgHIAbgSIAKgMIAKgQQADgJABgJQACgLABgPIhfAAIAAAxIgTAAIAAhCIA4AAIAAgiIAWAAIAAAiIA6AAQgCAjgCAJQgGAWgFAKQgLARgHAHQgQAOgOAIQgSAKgYAGQgGgOgEgFgADzBLIgHgGQANgEAOgGQAJgGAGgIQAGgIADgKQADgIACgQIAAgdIAWAAIAAAKIAlgjIh5AAIAAgSICLAAIADgBIANAQIgbAZIglAdIgHgIQgEAegCALQgEAOgIAJQgHAJgLAIQgJAHgUAIgABqBXIAAhdQgUANgRAKQgYANgMAGQgEgLgGgIQAcgLAVgNIAUgNIAWgSIAUgVIAVgXIARAOIguAtIAABugAknBBIAXgFQAIgDAEgDQAIgDAFgFQAFgFAFgGQAEgIACgIQACgIABgKQAAgXgPgOQgIgIgKgFQgKgEgMAAIgKArQgEAQgFALQgGAPgHALQgGALgGAGIgHAFQgEACgEAAQgHAAgEgDQgGgDgEgHQgHgIgDgLQgDgLAAgNQAAgPAGgOQAHgPAMgLQAZgXAogBQAVAAAUAKQAMAFAIAJQAFAEADAFIAFAMQAEAOAAAJQAAAMgDALQgCAKgGAJQgFAIgHAHQgHAHgLAGQgMAIgaAFQgDgKgFgIgAlIgqQgKAGgHAIQgGAJgEALQgDAIAAALQAAAJABAHQACAIAEAFQAEAHAFAAQADAAADgDQADgEAFgJIALgXQAFgNAEgPIAGgfQgPADgLAGgAoWBJIAAgvIBSAAIAAApIhBAAIAAAGgAoFA2IAvAAIAAgOIgvAAgAhmgeQgDgDgCAAIgDACIgxA6IgPgPIAmgqQAQgSAFgDQADgDAEABQAGgBAFADIBgBmIgRAOQgxg6gjglgAojgIIAAgqIBrAAIAAAqgAoQgWIBFAAIAAgOIhFAAgArygeIAAg1IB8AAIAAA1gArhgrIBZAAIAAgIIhZAAgArhg+IBZAAIAAgJIhZAAgAgyghIgGgFIgGgHQgBgEAAgEQAAgFABgEIAGgHQACgDAEgBQAFgBAEAAQAFAAADABIAHAEQADADACAEQABAEAAAFQAAAEgBAEQgCAEgDADIgHAFQgDABgFAAQgEAAgFgBgAgxg+QgDAEAAAFQAAAEADAEQAEACAEAAQAFAAADgCQADgEAAgEQAAgFgDgEQgDgCgFAAQgEAAgEACgApBg7IAAgPIBLAAIAAgRIAVAAIAAARIBLAAIAAAPg");
	this.shape.setTransform(0,10.4);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-78.1,-1.6,294.8,98);


(lib.t3 = function() {
	this.initialize();

	// Layer 1 copy 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFC538").s().p("AAABnIAAACQAAAXAAALIguAAQACgQAAgSIAAgUQglAMgYAFQgLACgGADIgMgvIAUgDIAAiVIgQABIAAgsQAOACAQAAIBYAAQASAAALgCIAAAQIBgABQANAAANgCIgBAVQgBAVgEAUQgCATgFATQgEASgHAPIgOAiQAMAPAKAIQAKAKASALQgSAdgIASQgRgNgMgKQgLgLgMgPQgNARgLAJQgLAKgVAPQgIgTgJgSgAAABcQAMgJALgKQAMgLAKgNQgIgQgNggQgFgPgMgvIAngOIgIAAQgWAAgJABIAAgSIgHAAgAhGAxIAagGIAAgUIgaAAgAA7geQAEAQAJAQQAIgUAEgQQAEgRACgYIgpAAQAFAdAFAQgAhGgMIAaAAIAAgVIgaAAgAhGhGIAaAAIAAgWIgaAAgAF0CLQADgTgBgYIAAjFQABgYgDgOIA0AAQgDAOAAAYIAADFQAAAcADAPgADKCFQgFgcgHgTQAkAFAVAAQAJAAAEgCQAFgBABgDQAEgHACgLIADgeIhpABQAGgZAFgaQADgdAAgZIBcABIAAgZIhDAAQgSAAgQACIAAguQAOADAVAAIBSAAQAWAAAKgCIgBAaIAAA6IABAZIgcgBIhEAAIgEAYIBmgBIgBALQgDA6gEASQgDAOgFAIQgEAJgGAGQgIAIgMACQgNADgWABgAJDCBQgPgGgJgJQgIgHgDgKQgEgKAAgKQAAgNAFgLQAFgLAKgIQAJgIANgEQAOgEAOAAIAWACIgBgXQAAgOACgVIAxACQgDAPAAATQgBANADAUQASAIAcASIAPAMIgXAwQgHgKgKgHQgJgIgMgHQAAAKgDAHQgDAHgHAGQgIAJgQAFQgOAFgTAAQgSAAgOgFgAJUBBQgHAEAAAHQAAAGAGAEQAGAFAJAAQAMgBAFgFQAGgEAAgKIAAgGQgLgFgKAAQgLAAgFAFgAolCFIAAgNIhrAAIglABIAAgtQAOADAXAAIBrAAIAAgkIheAAIglACIAAgsQATACASAAIBeAAIAAgfIhnAAQgbAAgKABIAAgsQAPACAWAAIB6AAIAbgBIAACmIABAlgANiCAQgSgDgWgFIgGg1QAVAIAVADQAUAEARAAQAPAAAMgDQANgDAIgEQAJgFAEgHQAGgGAAgIQAAgGgEgEQgDgFgFgDQgFgEgJgCQgHgBgLAAQgQAAgRAEQgRAFgPAJQgJAFgIAIIgygCIARh+IA0ACQgJAtgDAcIATgKIAUgIQAOgDAggCQAUAAAQAFQARAFALAKQANAHAFAMQAHANAAARQAAAJgCAKQgCAIgFAJQgEAIgGAGQgHAIgIAFIgRAKQgKAEgKACQgeAGgSAAQgUAAgQgCgAvzBIQAUAAAZgFQAagGAVgJQAOgFAMgHQALgGAKgIQALgIAJgJIASgTQAKgPAIgPQAHgPAHgVIAXAVQAJAJAMAHQgMAcgJAOQgLATgOAQQgMANgNAKQgNALgOAKQgOAIgQAIQgQAHgTAGQgeAJgYAEIgVAFgAmeBCQAXgDAXgFQAXgFAVgJQAOgGAMgHQANgHALgKQALgIAJgKQAJgLAJgNQAJgOAHgOQAHgNAGgSQALANAIAIQAIAHARAMQgKAWgKATQgLAQgMAOQgMAOgNAMQgNAMgRALQgeATgTAHQgnANgcAGIgWAFgAHOBCQALgOATgmQAKgRAPgqIgrgBIAAgwQARADAbAAIALAAIADgMQAEgRAAgTIA2AFQgCAHgDARIgEARQAdgDANgFIABAyIg2AEIghBWIgbA2gAvOAFQgVgJgZgKIAbgrQAbAKASAJQATALAUANIgZAsQgTgOgVgLgAl3gxQgOgKgcgRIAjgrQAcARASAMQARANATARIgjAvQgOgOgagWgAKnguQgXgKgbgJIAZgpQAdAKAUAJQAVAJAUAMIgVAsQgWgNgWgLgAu6hGQgUgKgWgIIAagqIAvATQAVAJASALIgbAuQgXgPgUgKgAN3hLQgngNgSgIIAYgrQALAFAOAFIAkALQAiAJAbAEIgRAwQgygLgWgHg");
	this.shape.setTransform(106.6,56.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FEFEFE").s().p("ApqHeQgNgCgLgEQgLgEgJgHQgJgGgIgJIArgcQAIAKAMAFQALAFAPAAQAMAAAKgDQAJgDAGgHQAEgFACgIQADgHAAgMQgLAKgNAFQgNAFgRAAIgTgCIgRgEIgOgIQgHgEgGgGQgFgGgFgHIgHgPQgEgLgCgaQAAgNAGgXIAIgPIAKgNIAMgKIAPgIIAQgFIATgBQAQAAANAEQANAEAMAJIAAgNIA7AAQgCASAAAYIAABpQAAAOgCALQgCALgEAKQgEAJgGAHQgGAIgIAFQgMAJgSAEQgTAFgWAAQgPAAgNgCgApbEZQgIAEgFAGQgFAGgDAIQgDAJAAAKQAAALADAIQADAIAFAGQAFAGAIADQAHAEAJAAQAJAAAIgEQAHgDAGgGQAGgGADgJQADgIAAgKQAAgKgDgIQgDgJgGgGQgGgGgHgDQgIgEgJAAQgJAAgHADgAAoGsQgLgCgJgDQgJgDgIgFQgFgFgHgHQgGgGgFgIQgFgIgEgJQgDgJgCgKQgCgLAAgLQAAgLACgKQACgKADgJQAEgJAFgIQAFgIAGgGQAHgHAFgFQAIgFAJgDQAKgDAKgCQAKgCALAAQAMAAAKACQAKACAJADQAJADAIAFQAIAFAHAHQAGAGAFAIQAFAHADAJQAEAJACAKQABALAAALQAAALgBAKQgCAKgEAJQgDAJgFAIQgFAIgHAHQgGAGgIAFQgIAFgJAEQgJADgLACQgKACgLAAQgLAAgKgCgAAsEaQgIADgFAHQgGAHgCAKQgDAKAAAMQAAAMADAKQACAKAGAHQAFAHAIAEQAIADAJAAQAKAAAIgDQAHgEAGgHQAFgGADgKQACgKAAgMQAAgNgCgKQgDgKgFgHQgGgHgHgDQgIgEgJAAQgKAAgIAEgAhfGnIiIABQADgOAAgeIAAieQAAgdgDgTIBCAAQgDARAAAeIAACVIBJAAQAhAAARgCIAAA5QgQgCgiAAgAFTGnQgBgLgIgYIgVhIIgWBIQgIAXgCAMIgzAAQgCgOgHgVIgviUIBBAAQABAPAFAUIAPBFIAfhoIAsAAQABAMAHAXIAWBFIAPhCQAFgXABgPIBBAAIgvCUQgHAVgCAOgAlHGnQADgTAAgaIAAg+QAAgPgFgHQgHgIgMAAQgNAAgMAIQgMAIgJAPIAAA9QAAAYADAVIg+AAQACgTAAgaIAAifQAAgegCgPIA+AAQgDARAAAcIAAApIAOgLIAOgIQALgEAXgBQAQAAAMAEQAMAEAIAIQAJAJAEAMQAEAMAAASIAABLQAAAZADAUgAsCGnQACgUAAgZIAAhdQAAgbgCgSIA+AAQgCAQAAAdIAABdQAAAYACAVgAtlGnQACgRAAgbIAAg7IhlAAIAAA7QAAAaACASIhAAAQACgQAAgcIAAihQAAgbgCgRIBAAAQgCASAAAaIAAAyIBlAAIAAgyQAAgdgCgPIBAAAQgCAQAAAcIAAChQAAAYACAUgAsBDaIAAgsIA8AAIAAAsgAgtjjQgHgLgMgOQAVgEAOgEQANgEALgGQAIgGAIgGQAHgGAGgHQAFgHAEgIQADgIACgKQACgLABg1IAAgfQAAgagCgPIA7AAIgCAoIAAAjQAAAfgCAWQgBAWgEANQgDAMgGALQgFALgIAJQgIAJgKAJQgKAIgMAHQgNAHgOAGQgLAFgXAGQgFgPgGgLgAl/jhQgIgJgPgNIAYgLQALgGAJgHIAPgOQAHgIAFgJIAJgSQADgKABgKIABgOIhAAAQgZAAgSABIAAg0QAPACAdAAIBCAAIAAgjQAAgTgBgNIA5AAQgBAJgBAYIAAAiIAyAAQAdAAAQgCIAAA0QgTgBgZAAIg1AAQgDAdgEASQgFASgJARQgJAPgMANQgMANgPALQgMAJgTAKQgIgOgJgKgAM2jjQgHgJgPgPQAWgIAjgSQAMgHALgIQALgIAKgKIARgUQAIgKAGgLQAGgLAFgMIAIgZIh+AAQgjAAgOABIAAg2QAWADAcAAICQAAIAJgBQACgNAJgIQAJgIANAAQAHAAAGADQAGACAFAFQAEAFADAGQADAGAAAHQAAAHgDAGQgCAFgEAFQgFAFgGACQgGADgHABIgDAKQgFAUgHASQgHATgJARQgKASgLAPQgLAPgNANQgbAYgQAKQgiAVgWAKQgIgQgIgKgAPrnFQgDADAAAFQAAAFADADQAEAEAFAAQAFAAAEgEQADgDAAgFQAAgFgDgDQgEgEgFAAQgFAAgEAEgAJmjMQADgPAAgWIAAhfQgLAQgNAPQgNAPgQANQgPAOgSAMQgSAMgVAMQgIgPgHgJQgHgJgOgNQAXgKATgMQASgLAQgMQAPgNAMgOQANgOAKgQIg+AAQgbAAgSACIAAg0QAVADAZAAIBeAAIAAgPIgCgiIA4AAQgBANAAAQIAAAUIATAAQAbAAAQgCIAAAzQgOgCgcAAIgTAAIABCCQAAAXACASgApljNQACgTAAgdIAAhTQgXANgWAKQgVAKggALQgGgPgGgKQgGgJgLgOQAZgHAVgIQAVgIATgJQATgJASgMQASgLASgOQAUgPAOgOQAOgPAHgLIAxAgIgMAMQgSASgRAOQgQAPgSANIAABzQAAAdABAUgAs+kEQgQgggHgTQgIgYgHgcQgGgcgEgcIgEgYIA0gKQAFArAGAXQAGAXAIAWQAHAVAKASQAJASAaAiQgQAJgKAIQgKAIgMANQgVgfgIgQgAv7jpQgLgIgPgIQAOgQAKgPQAKgPAJgWQAIgUAMgvIAGgjQACgSAAgQIA5ALIgFAaQgEAigFAWQgFAXgHAWQgNAmgJAQQgSAfgNARQgMgMgLgIgAFzk4IiPAAQgoAAgWACIAAg6QAeADAgAAICPAAQAeAAAfgDIAAA6QgRgCgsAAgAhilCQACgMAAgfIAAg8QAAgXgCgQIA6AAQgBARAAAXIAAA8QAAAcABAOgAs2m2IAYgIQAKATAHAWIgZAJQgFgSgLgYgAsWnBIAYgIQANAaAEAOIgYAJQgGgTgLgWg");
	this.shape_1.setTransform(107,58.5);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,7.6,220.7,170.2);


(lib.t2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFC538").s().p("AlvCOQABgRAAgUIAAgIIhHAAQgZAAgRACIAAgtIATABIgWgnIAOgGIA2gkIAWAkQgOANgMAHIgmAaIBaAAIAAgNIgZABIAChNQgGAHgIAHQgGgNgHgJIgTAYIgYgRIgagOIAdgiQATAKAQAJQAOgLAUgZIANgVIAJgVIAuAHQgHAQgHAKIAbAAQAKgQAGgQIAsAGIgPAaIAVAAQATAAANgCIAAAnQgKgCgQAAIgiAAIAAAKIAbAAIAZgBIAAAcIgZgBIgbAAIAAALIAbAAIAZgBIAAAbIgZAAIgbAAIAAAIIAiAAQASAAALgCIAAAmQgKgBgVAAIhTAAIAAANIBOAAQAYAAANgCIAAAtQgRgCgZAAIhJAAIAAAHQAAAYABAOgAlaAIIAkAAIAAgIIgkAAgAlagaIAkAAIAAgLIgkAAgAlag/IAkAAIAAgKIgkAAgAq9CJQgBgOgDgKQgCgJgFgNQAZADAOAAQAGAAACgBQACgCAAgEIAAi/QAAgTgCgOIAzAAQgCAOAAATIAAAWQAIAdAIAPQARgQAMgPQALgOAIgPIArAfIgRAUQgfAhgTAOQAMAQAPAPQANANAMAIQALAIAQAIQgKAMgGAKIgPAbQgTgOgMgLQgNgNgMgQQgKgNgIgNIgPgcIAAASIABATIAAA3QAAALgCAHQgDAHgFAEQgFAFgJACQgJABgPAAgAIhB5IDDj8IAQAMIjED8gAK7B9QgMgFgJgIQgJgJgFgNQgEgOAAgRQAAgRAEgOQAFgNAJgJQAJgGAMgFQAMgEAOAAQAPAAAMAFQAMAEAJAHQAIAJAEANQAEANAAARQAAARgEAOQgFANgJAJQgIAIgMAFQgMAEgOAAQgPAAgLgEgALLAYQgFACgCAFQgDAEgCAHIAAAhQABAIADAEQADAFAFADQAEACAGAAQAGAAAEgCQAEgDADgEQADgFABgIIACgRQAAgSgGgJQgGgKgLAAQgGAAgEADgAFrB/QgKgCgJgEQgJgDgIgFIgPgMQgIgIgFgIQgGgJgDgJQgGgQgDgRQgDgRAAgRQAAgPAGgfQADgOAKgXQAHgLAJgJQAJgJAMgGQALgGANgDQAMgDAPAAIAVACQAKACAJADQAJAEAIAFQAJAFAGAHQAIAHAFAJQAGAIADAJQAGAQADASQADARAAASQgCAegDAPQgIAbgGAKQgHALgJAJQgJAIgLAGQgLAGgNADQgNADgOAAQgMAAgKgBgAFuhKQgJAFgFAKQgGAKgDAOQgDAPAAASQAAASADAQQADAPAFAKQAGAKAIAFQAJAFALAAQALAAAIgFQAIgFAGgKQAGgKADgPQACgPAAgSQAAgTgDgPQgDgOgFgKQgGgKgIgFQgJgFgKAAQgLAAgIAFgACEB/QgKgCgJgEQgKgDgIgFIgPgMQgHgIgGgIQgFgJgEgJQgFgQgDgRQgDgRAAgRQAAgPAFgfQADgOALgXQAHgLAJgJQAJgJALgGQALgGANgDQANgDAOAAIAVACQAKACAKADQAJAEAIAFQAIAFAHAHQAHAHAGAJQAGAIADAJQAGAQADASQADARAAASQgCAegEAPQgIAbgFAKQgHALgJAJQgJAIgMAGQgLAGgNADQgNADgOAAQgLAAgKgBgACGhKQgIAFgGAKQgGAKgDAOQgDAPAAASQAAASADAQQADAPAGAKQAFAKAJAFQAIAFALAAQALAAAJgFQAIgFAGgKQAFgKADgPQADgPAAgSQAAgTgDgPQgDgOgGgKQgFgKgJgFQgIgFgLAAQgKAAgJAFgAgcB7IhpAAQgeAAgPABQACgUAEgPQAGgTALgRQAHgLATgUQAMgLAqgbQATgNAGgIQAHgIAAgKQAAgLgJgHQgJgGgOAAQgLAAgIADQgIAEgEAIQgGAJgCAQIg/gHQADgTAFgMQAFgLAJgLQAGgIAJgFQAIgGAKgEQAKgEAMgCQALgCANAAQAQAAANADQANACALAFQALAFAJAHQAGAHAGAJQAKAQAAATQAAAIgCAIQgCAHgDAHQgEAHgFAHIgKAMQgKAGghAYQgUANgKAJQgJAKgFAKIBFAAQAeAAAQgDIAAA5QgWgCgbAAgAsCBfIgSgTQAOgLAJgKQAKgKAJgNQALgPAGgOQAHgMAFgUIgcAAQgTAAgNACIAAgwQALACAYAAIAfAAQARAAAIgBIAWAZIgHAVQgHAcgIATQgIAUgMATQgKARgLANQgLANgQAPgAImAFQgMgEgJgGQgIgJgFgOQgFgNAAgRQAAgRAFgOQAFgNAJgJQAIgIAMgFQAMgEAOAAQAOAAAMAEQAMAFAJAIQAJAJAEANQAFAOAAARQAAARgFAOQgFANgJAJQgIAGgMAEQgMAFgOAAQgOAAgMgFgAI2hdQgEACgDAFIgEALIgCARIABAQQACAHADAFQADAFAEACQAEADAGAAQAGAAAEgDQAEgCADgFQADgFACgHIAAghQgCgHgDgEQgDgFgEgCQgEgDgGAAQgFAAgFADgAm+heQgLgHgPgIIAeggQAgARASAOIgdAjQgOgMgLgHg");
	this.shape.setTransform(81.4,56.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FEFEFE").s().p("AGcGxQgHgKgMgOQAWgFAigNQALgGAKgGIASgOQAJgJAGgJQAIgJAEgLQAGgKADgNQADgMACgOIiDAAIAAAbQAAAVACALIg5AAQACgRABgQIgChKIAmABIA1AAIAAgSIgCgcIA6AAQgCAOABAOIAAASIA2AAQARAAAHgDIAXAXQgDAGgCANQgEAbgFATQgGAUgIARQgHANgHALQgIALgKAKQgKALgKAIIgZARIgaANIgiANQgIgQgGgLgAA1GxQgHgKgMgNQARgFAYgNQALgGARgRQAFgHAEgIQADgIACgJQAEgNABgjQAAgNgCgIIA5AAIgCAaIAAALIAGgEQAMgGASgQQAJgIAMgVIiPAAQgbAAgVACIAAg1QASADAfAAICdAAQASAAAIgDIAcAfQgFAGgEAKQgIARgIAOQgIAOgKAMQgLAMgMALQgMAKgPAJIgPgSIgSgPQgCAYgEARQgEARgIAPQgIAPgMAMQgLANgQALQgWAOgUAJQgJgSgGgIgAiUHGQACgTAAgdIAAhTQgXANgWAKQgVAKggALQgHgPgGgKQgFgJgLgOQAYgHAWgIQAUgIATgJQAUgJASgMQASgLASgOQATgPAPgOQAOgPAGgLIAyAgIgNAMQgRASgRAOQgRAPgRANIAABzQgBAdACAUgArgGqQgFgKgJgMQAUgCAQgEQAPgDAMgHQAIgEAHgHQAHgHAFgJQAEgJACgLQADgKAAgMQAAgKgCgIQgBgJgEgIQgDgHgFgGQgFgGgGgFQgLgJgPgCQgHAwgGAVQgLAngJASQgHAOgGALQgHAKgJAHQgIAGgJAEQgIADgLAAQgPAAgMgHQgMgHgKgMQgJgNgFgRQgFgRAAgUQAAgNADgNQACgMAEgMQAEgMAHgKQAGgLAIgJQALgLAMgIQAMgIANgGQAOgFAQgDQAPgDAQAAQAPAAAOADQAOACAMAFQANAEALAHQAKAHAJAJQAHAIAGAJQAFAJAEALQAEAKABAMQACAMAAAMQAAAPgDAOQgCAOgFAMQgGAMgHALQgHALgKAIIgQANQgIAFgLAEQgeAJgVAEQgFgQgGgLgAsED/QgIADgIAHQgHAGgGAIQgGAJgEAJQgEAJgDAKQgCAKAAAKQAAAQAFALQAGALAIAAQAFAAAGgIQAGgIAHgRQAIgUAFgZQAHgYACgWQgJABgIAEgAKuHEQACgUAAgaIAAiuQAAgZgCgSIA6AAQgBAKAAAhIAAApQAZAJAsASQAWAKAtAaIgcAzQgXgPgZgOQgYgOgXgJIgNgGIAABNQAAAeABAQgAmAFyIhDhLQgHgHgEAAQgEAAgCACIgKANIg2BEIgLAOIgkgzQAKgHAPgSQAQgSAaghQALgOAPgLQALgGALAAQAOAAAJAGQAKAGASAVQAXAaAVAVIAwAvQASARAPAKIgbA6QgwgugVgXgAlnEQQgFgCgFgFQgFgEgDgGQgCgHAAgGQAAgHACgGQADgHAFgEQAFgFAFgCQAHgDAHAAQAGAAAGADQAGACAFAFQAEAEADAHQADAGgBAHQABAGgDAHQgDAGgEAEQgFAFgGACQgGADgGAAQgHAAgHgDgAliDpQgDAEgBAFQABAFADADQADAEAGAAQAEAAADgEQAEgDAAgFQAAgFgDgEQgDgDgFAAQgGAAgDADgAo3jUQAUgFALgEQAMgFAKgHQAIgHAEgJQAFgJABgOQgOAKgOAIQgPAHgSAHQgGgTgPgZQASgEAbgLQAMgGASgQIgwABQABgMAAgWIAAg+QAAgXgBgMIDJABQAXAAANgBQgCALAAAYIAAA+QAAAXACALIgzgBQAOAMAUAJQAUAJAXAGQgPAagFATIg5gcIAAA4QAAAUACAPIgyAAQACgSAAgRIgBhQIAQAAQgOgNgMgQIgYAAQgKAPgOAOIAVAAIgBANQgDAegEALQgDAJgFAIQgFAHgGAHQgLAMgPAIQgPAHgXAGQgOgWgNgQgAmclkIAzAAIAAgMIgzAAgAn4lkIAwAAIAAgMIgwAAgAmcmQIAzAAIAAgNIgzAAgAn4mQIAwAAIAAgNIgwAAgAr4ivQACgNABgQIAAgaIgUARIgVANQgiARgWAGQgEgMgGgJIgOgUQAUgDAfgKQAPgGAXgOIgqAAQgVAAgSACIAAgmQAQACAXAAIBJAAIAAgKIhZACIAAggIBZABIAAgJIhmABIAAgjIA7ABIgIgOIg/ACIAAgoQAOABAUAAQgGgLgLgNIArgOQAJAPALAXIAJAAIgCgpIAtAAIgBApIAMAAIgBgpIAtAAIgBAWIAAATIAJAAQAKgPAJgXIArAOIgPAYQAUAAAPgBIAAAoQgRgCgVAAIgZAAIgHAOIAcAAIAdgBIAAAjIgdgBIhMAAIAAAJIA/AAIAegBIAAAgQgMgCgSAAIg/AAIAAAKIBNAAQAaAAANgCIAAAmQgTgCgUAAIguAAQALAHAbAMQAPAFAmAHQgPAagHARQgqgNgQgJQgNgHgKgIQgLgHgJgKIABAbQAAATABAKgArzluIAqAAIAFgOIg1AAgAgti9QgOgGgMgIQgZAQgVAKQgFgOgIgNQAAAPACANIguAAIABgcIhPANIgNACIgJgrIAcgBIAAhVIgaABIAAglQALACAYAAIDRAAQAWAAAKgCIAAAlQgLgBgWAAIhlAAIAABjQAPgGALgHQgKgKgLgTIAfgMIgeABIAAgnIBOACQAPAAAHgCIAVAYIgHANQgSAdgMANQAPAGAgAIQgMAYgFASQgWgHgNgGgAjMjtIAfgDIAAgKIgfAAgAhJj+QAJgJAHgKIggAAQAIAMAIAHgAjMkSIAfAAIAAgLIgfAAgAjMk1IAfAAIAAgJIgfAAgAAgiwQACgNAAgXIgBhqIDpABQAUAAAKgBIAAAbIAABGQgBASgCAHQgCAHgGAEQgGAEgKABQgKACgQAAIgXgBQAAgMgDgMIhPAAIAAALIgsAAIAChBIgBgSIB1ABIAWgBIgBA5IALAAQAGAAABgGIAAg6IitAAIAABGQAAAYACAMgACKjqIA3AAIAAgLIg3AAgABDlEIABgVIgBgyICnABIAdgBIAABHgABwlhIBpAAIAAgMIhpAAgAjznEIC9ABIAggBQgCAKAAATIAAAjQAAASACAKIjdAAgAjGmBICCAAIAAgJIiCAAgAjGmfICCAAIAAgJIiCAAgAEOmSIjTAAQgVAAgMACIAAgqQAQACATAAIBOAAQAAgLgCgIIAyAAIAAATIBTAAQAUAAANgCIAAAqQgMgCgVAAg");
	this.shape_1.setTransform(90.6,56.4);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,7.6,221.6,478.5);


(lib.t1 = function() {
	this.initialize();

	// Layer 1 copy 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFC538").s().p("AmuEXQgGgJgLgLQAIgPAHgYQAEgSACgWQACgYAAgcIgBgkIA+ABIgHgSIgYAAQgVABgLABIAAgrQAOACAWAAIBEAAQAAgHgCgKIAzAAIgCARIBDAAQAXAAAOgCIAAArQgMgBgVgBIgTAAIgIASIAiAAIAggBIAAAqQgMgCgUAAIicAAIAkAKIgEALIAWAAIgBgPIAvAAIgCAPIAxAAIAcgCIAAAoIgcgBIgxAAIAAANIApAAIAbgBIAAAmIgbgBIgpAAIAAAOIA7AAQAPAAAOgBIAAAqIgegBIjAABIAAgqIBaABIAAgOIg6ABIAAgWIgLAOQgIgMgJgLQgGAmgFAQQgLAcgHALQgJgQgHgHgAlbDKIAwABIAAgNIgoAAgAl8COQAAAUgCARQALgOAGgPIAHgSIgWAAgAk6BdIAjAAIAHgSIgxAAgAobEiQgegOgSgKIAYgNIhQAAIAbANQgfASgPAFQgfAKgYADQgOgVgLgNQAagCARgDQARgEAOgGIgpAAIAAh2IgRAHIgQgpQAOgDAUgHQAUgIARgIIAMAgIAZgGQALgDAIgFQAHgFAFgFQAFgHACgHIgSAAQgRAQgQAKQgLgOgQgOQALgGAUgSQANgPAFgMIAuAGIgIANIBPAAIAVgBIAYASIgLATQgGAJgPATQgSgJgVgGQAJgIAGgHIgfAAQAEAKAHAHQAHAIAMAFQALAFAQACQAPADATABQgLAYgEAPIgUgDIAABKQAAAZABAIIgqAAQAQAGARADQASADAaACQgQATgKAQQgngHgQgFgAqYDhIB9AAIAAgJIh9AAgAqYDCIB9AAIAAgIIh9AAgAqYClIB9AAIAAgIIh9AAgApLB3QgJAHgPAFIBKAAQgMgFgHgHQgIgGgIgLQgHAKgIAHgAq+CDIAsAAIgKgQgAIIEPQgHgJgQgPQAXgJAjgRQAMgHALgJQAKgHAKgLIASgUQAHgKAGgKQAHgMAEgMIAIgYIh9AAQgkAAgOABIAAg2QAWACAdABICPAAIAJgBQADgNAJgIQAJgIANAAQAGAAAHADQAGACAEAFQAFAFACAFQADAGAAAHQAAAHgCAHQgDAFgEAEQgEAFgHADQgGADgHAAIgDALQgEATgHATQgHATgKARQgJARgLAPQgMAQgNANQgaAYgQAKQgjAUgWALQgIgRgHgJgAK9AtQgEADAAAEQAAAGAEADQADAEAGAAQAFAAADgEQAEgDAAgGQAAgEgEgDQgDgFgFAAQgGAAgDAFgAE4EmQACgPAAgWIAAhfQgLAQgNAOQgNAQgPANQgQAOgSAMQgSAMgVAMQgHgPgHgJQgIgKgNgMQAXgKASgMQATgLAPgMQAPgNANgOQAMgOALgQIg+AAQgbAAgSABIAAgzQAUACAaAAIBeAAIgBgPIgBghIA4AAQgCANAAAQIAAATIATAAQAbAAAQgBIAAAyQgNgBgdAAIgTAAIACCCQAAAWACATgAgwEcIgVgFQgJgDgHgFQgHgFgFgFQgFgHgEgHQgDgHgCgJQgCgIAAgJQAAgIACgJQACgJAEgHQAEgJAGgHQAGgHAHgFQAKgJAbgPQgHgagKg1IgFgTIA2gJQABAPAFAZQAFAZAEAZIAjgLIA0gRIARA2QgWADgeAHQgdAIgZAJQgOAFgLAGQgLAFgHAGQgIAGgDAHQgEAGAAAGQAAAHAEAGQADAEAHADQAHAEAMABQALACAOAAQAUAAAYgCQAXgDAVgFIAQgEIADA5IgaACQg1AGgWAAQgmgCgQgEgArhAxIAbgfQAeAOATANIgcAiQgTgPgdgPgACpgnQgGgJgLgKQAIgPAFgPQAGgQADgUQADgUABgcIABhBQAAgkgBgTIDWABQAbAAANgBIAAAsIglgBIgxAAIgFANIAsAAIAegBQgCALAAARIAABDQAAAQACAMIgdAAIgnAAIAAA5QAAANgDAHQgDAIgIAEQgFADgLABIgxABQgBgRgEgQQgLASgQAPQgTgVgPgKQAQgOAKgPQALgQAGgRIAqAOQgGARgLATIAVACQALAAAAgGIAAgvIhDAAIAAh7IA7ABIAFgNIhLAAIAAAcQgBA8gDAZQgGAvgFAQQgFAQgFANQgGANgIAPgAEWiVIBbAAIAAgLIhbAAgAEWi/IBbAAIAAgLIhbAAgAjhgSIAAgJIiZAAIAAAJIgtAAQABgRAAgSIgBhVIDTABQAUABAMgCIgBAhIAAA0QAAAWACANgAkZg7IA4AAIAAgKIg4AAgAl6g7IA1AAIAAgKIg1AAgAkZhgIA4AAIAAgKIg4AAgAl6hgIA1AAIAAgKIg1AAgAn0gWIjKAAQgUAAgQABIAAgmQAQACAUAAIAiAAIgGgNIglABIAAhBIDbAAIAABBIgdgBIgGAAIgGANIAhAAQAUAAAQgCIAAAmQgQgBgUAAgApsg5IAmAAIAFgNIgxAAgAqZhhIB/AAIAAgKIh/AAgAF5g4QgSgagHgPIAogRQAIAQANAPQAMAOARALQgSATgOASQgXgWgKgNgAgagbQgPgGgJgJQgHgHgEgKQgEgJAAgLQAAgNAFgLQAFgLAKgHQAJgJANgDQAOgFANAAIAVABIgBgXQAAgQACgTIAxACQgDAOAAAUQAAAOACAUQASAIAcASIAPANIgWAvQgIgJgKgJQgJgHgMgIQAAAKgDAIQgDAHgHAHQgIAIgPAFQgPAFgSAAQgQAAgPgFgAgJhcQgHAFAAAHQAAAGAGAFQAGADAIAAQALAAAGgEQAFgGAAgJIAAgHQgLgDgKAAQgIAAgGADgAiPhaQALgOAUglQAJgUAPgqIgqAAIAAgxQAQAEAcAAIALgBIACgNQAEgRABgSIA2AFQgDAIgDAQIgEARQAbgDANgEIABAwIg0AGIghBWIgaA3gAn4iOIjDAAQgVAAgPACIAAglQAMABAYABIDDAAQAZgBALgBIAAAlQgPgCgVAAgAmSiQIAAg/IDKAAIgBAWIAAATIABAWgAllirIBwAAIAAgKIhwAAgABIjLQgXgLgagJIAYgqQAdALAUAJQAVAJAVAMIgWAsQgVgNgXgKgAn/i4IjTABIAAhmQAKABAYAAIAhAAIgBgRIAsAAIgBARIAXAAIgCgRIAtAAIgCARIAjAAQAXAAALgBIgBAbIAAAvIABAcIgfgBgAoljRIAYAAIAAgLIgYAAgApljRIAXAAIAAgLIgXAAgAqljRIAXAAIAAgLIgXAAgAolj0IAYAAIAAgLIgYAAgAplj0IAXAAIAAgLIgXAAgAqlj0IAXAAIAAgLIgXAAgAjwjWIiPABIAAgeICPACQAMAAAJgCIAAAeIgVgBgAjTjaIAAgfIi0AAIAAAfIgtAAQABgKAAgMIgBguQAMABAYABIBJAAIgBgRIAyAAIgCARIBOAAQAXgBANgBQgCAJAAANIAAAZQAAAOACAHg");
	this.shape.setTransform(77.3,40.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FEFEFE").s().p("AieEKIgIATQgQgKgKgJQgJgIgJgLQgJAOgLAKQgMAKgUAKIgLgTIgPgSQASgIAKgHQAHgFAEgFQAEgFAEgHIgLAAIgeABIAAgqIAfABIASAAIAAgEIgBgLIAtAAIgCAPIArgBIAAAqIgmgBQAHAIAKAGQAKAGAPAGIgKAQQANgFAKgGQAJgGAKgIIgdAAIABhqQgJALgHAWQgOgIgHgHQgIgGgGgIIABAXIgrAAIACgWIgSATQgIAHgMAIQgGgRgMgVQANgFAKgHQAKgHAJgJIgkACIAAgnIAWACQgJgQgQgTIAegRQALAMALARIAAgKIgBgTIAsAAIgBATIAAALQAKgNAIgRIAcAOIAAgIIAiABIBIAAIAjgBIAAArQgNgCgWAAIgNAAIgGAOIAvgBIgBAdIAABiIABAiIgagBIgFAAQAKAIAKAHQAKAGAMAHQgSAVgJAOQgQgKgKgJIgYgVQgOAOgMAIQgLAIgWAKQgMgRgLgOgAhPD8IAYgSIgsAAgAhhDGIArAAIAAgLIgrAAgAhhCfIArAAIAAgLIgrAAgAiMB8IgBgyIAnABIAFgOIgTAAQgTAAgJACIAAgdIgWAgIASgBIAAAlIgcgBQAHAHAIAFQAJAGAMAFgAhhB4IArAAIAAgLIgrAAgAi+BCIAWAAIgWgOgAkCBCIAaAAIAAgPgAonElQACgRAAgTIABg5QgFAOgFAJIgNAUIgSgtQAMgNAKgTQAJgSAGgSIgeACIAAgsQAJABAMAAIAMAAIAAgWIgWAEQgGgVgJgTQAagDAZgHQAZgGAKgGIAWAmIgcAJIAAAhIATgBIAAgcIBEABIAAgIIgzABQgFgTgJgOIAdAAQAYAAAxgDQAWgCAbgGIAZAhIgIACQgVADgpADIAAAKIAsAAQASAAAMgCIAAAkQgJgBgSAAIgvAAIAAAJIBAgBQgCALAAAOIAAAwQAAARACALIgZgBIgnAAIAAAJIAkAAQATAAALgBIAAAhIgegBIgkAAIAAAKIApAAIAhgBIAAAmQgOgCgWAAIh2AAQgXAAgNACIAAgmIBLABIAAgKIhBABIAAghQALABAUAAIAiAAIAAgJIg9ABIABgmQgJAPgGAWIgNgVIABBMQAAAYACAMgAl6CwIAWAAIAAgMIgWAAgAm4CwIAVAAIAAgMIgVAAgAntCVIAOANIgBg8IA9ABIAAgJIhDABIAAAkIgTgBgAl6CMIAWAAIAAgLIgWAAgAm4CMIAVAAIAAgLIgVAAgAhigfIAAgNIhqAAIglABIAAgsQANACAYAAIBqAAIAAgjIheAAIglABIAAgsQATACASAAIBeAAIAAghIhnAAQgaAAgLACIAAgtQAPACAWAAIB6AAIAcgBIgBCoIABAlgAHFg9QgFgKgKgMQAVgCAQgEQAOgDAMgHQAJgEAHgHQAHgHAEgJQAFgJACgLQADgKAAgMQAAgKgCgIQgCgJgDgIQgDgHgFgGQgFgGgHgFQgKgJgPgCQgIAwgFAVQgMAngIASQgHAOgHALQgHAKgIAHQgIAGgJAEQgIADgLAAQgPAAgMgHQgNgHgJgMQgJgNgFgRQgFgRAAgUQAAgNACgNQACgMAFgMQAEgMAGgKQAHgLAIgJQAKgLAMgIQAMgIAOgGQAOgFAPgDQAPgDARAAQAPAAAOADQAOACAMAFQANAEALAHQAKAHAJAJQAHAIAFAJQAGAJADALQAEAKACAMQACAMAAAMQAAAPgDAOQgCAOgFAMQgGAMgHALQgIALgJAIIgQANQgJAFgKAEQgeAJgVAEQgFgQgGgLgAGhjoQgIADgIAHQgHAGgGAIQgGAJgEAJQgFAJgCAKQgCAKAAAKQAAAQAFALQAFALAIAAQAGAAAGgIQAGgIAHgRQAHgUAGgZQAHgYACgWQgJABgIAEgAowhcQAUAAAZgFQAagGAWgIQANgGAMgGQALgHALgIQAKgHAJgKIASgVQALgPAHgPQAHgOAIgWIAWAWQAJAIANAHQgMAcgKARQgLASgOAQQgMANgMALQgNALgOAJQgPAJgQAHQgQAHgSAGQgfAJgYAEIgVAFgAAjhiQAXgCAXgFQAXgGAVgJQAPgGAMgHQAMgHALgJQALgJAJgLQAKgLAIgOQAKgOAGgOQAHgNAHgSQAKANAJAIQAHAHASAMQgLAXgKASQgLASgMAOQgLAPgOAMQgNAMgQAKQgfATgTAHQgnANgcAGIgVAFgAoLifQgVgLgZgKIAcgrQAaAKATAKQATAKAUANIgaAvQgTgPgVgLgABKjXQgNgKgdgRIAjgqQAcAQASANQARAMATARIgjAvQgNgNgbgXgAn2jsQgUgKgXgIIAagqIAvATQAVAJATALIgbAuQgXgPgUgKg");
	this.shape_1.setTransform(61.5,105.3);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,7.6,220.7,161.6);


(lib.strip = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFC538").s().p("AgdTiMAAAgnDIA7AAMAAAAnDg");
	this.shape.setTransform(3,125);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,6,250);


(lib.logo_mc = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2F2E2E").s().p("AAVA8QgjAAgIgCQgPgDgGgHQgGgIgCgNQgBgFAAgUQAAgVABgGQADgPAHgIQAJgIAZgCIAjgBQAoAAALADQARADAEANQADAHAAAPIgkAAQAAgEgCgFQgEgEgJAAIgzAAIgFABQgGACgDAFQgCAFAAAVQAAAPACAEQACAIAJABIAWABIAiAAQAMgBABgJIAAgIIguAAIAAgUIBSAAIAAAPQAAAZgDAHQgDAJgGAFQgJAEgOABgADrA7IAAguIhTAAIAAAuIglAAIAAh1IAlAAIAAAsIBTAAIAAgsIAlAAIAAB1gAhkA7IAAh1IAlAAIAAB1gAiWA7IAAguIhUAAIAAAuIgmAAIAAh1IAmAAIAAAsIBUAAIAAgsIAlAAIAAB1g");
	this.shape.setTransform(31.8,15.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FEFEFE").s().p("AheA6QgOgCgGgIQgHgFgCgOQgCgIAAgVIABgUQgBgFADgHQADgMAJgHQAKgGAXgCIAhAAQAqAAAKABQAPADAGAIQAHAJABAMQACAKAAARQAAAbgFAKQgEAKgJAFQgIAEgFABIgVACIgdAAQgqAAgKgCgAhHgdQgLABgDAHQgCAFAAAQQAAAQACAGQADAGAMACQAHABAUAAQAbAAAHgCQAHgBACgFQACgFgBgIIABgKQAAgQgCgGQAAgEgDgBQgFgDgHAAIgbAAQgZAAgEABgAkSA7IAAh1IAlAAIAABXIBkAAIAAAegACyA7IgVhJIgXBJIgzAAIgsh2IAoAAIAdBRIAahRIAuAAIAZBRIAdhRIAoAAIgtB2g");
	this.shape_1.setTransform(97.6,21.9);

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E1E0DF").s().p("AAABlIk8A5IAAkCIE8g5IE9A5IAAECg");
	this.shape_2.setTransform(31.8,15.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B6B6A").s().p("Ak8BlIAAkCIE8A5IE9g5IAAECIk9A5g");
	this.shape_3.setTransform(97.2,21.8);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,129,37.7);


(lib.btnbg = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F0F0F0").s().p("A0TDvIAAneMAonAAAIAAHeg");
	this.shape.setTransform(130,24);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FCCD2A").s().p("A0TAPIAAgdMAonAAAIAAAdg");
	this.shape_1.setTransform(130,49.5);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,260,51);


(lib.bg2b = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bg2_blur();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,375,250);


(lib.bg2a = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bg2();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,375,250);


(lib.bg1_1 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.bg1();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib._bg = function() {
	this.initialize();

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A3bTiMAAAgnDMAu2AAAMAAAAnDg");
	this.shape.setTransform(150,125);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib._clicktag = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#424242").s().p("A3bTiMAAAgnDMAu2AAAMAAAAnDg");
	this.shape.setTransform(150,125);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{on:1,off:7});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_6 = function() {
		this.stop();
	}
	this.frame_12 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(6).call(this.frame_6).wait(6).call(this.frame_12).wait(1));

	// t
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Ah4AwQgQgPgWgRIgIgGIgDgFQgCgEAAgCIABgHIAEgGIAMgKIAUgQIAOgMIAGgIIAWAPIgQAOIggAZQgEAEAAABIABABIALAIQAOAKAZAVIAEAEIgSATQgEgGgJgIgAmAA9IAAgRIAAgKIgIAAIgPABIAAgUIAPABIAIAAIAAgJIgTABIAAgRIATABIAAgIIgJAAIgNAAIAAgTIALABQgCgGgIgNIASgHQAIANADAHIgOAGIASAAQAFgJAFgSIAUAHIgJAUIABAAIAMgBIAAATIgOAAIgMAAIAAAIIAKAAIANgBIAAARIgNgBIgKAAIAAAJIANAAIAPgBIAAAUIgOgBIgOAAIAAAKIABARgAnHA9IAAgsIAlABIAIgBIAAAqIgRAAIAAgEIgJAAIAAAGgAm1AoIAKAAIAAgIIgKAAgAGHA4IgRgDIgDgXIATAEIAQACIAMgBIAJgDQADgCACgDQADgDAAgEQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAIgDgEIgGgCIgIAAIgPABQgHACgGAEQgEACgEAEIgVgBIAAgCIAHg0IAXACIgGAeIAIgDIAJgDQAGgCAOgBQAJAAAHACQAHADAFAEQAFACADAFQADAGAAAHIgBAIIgDAHQgCAEgDADIgGAFIgHAEIgJADQgNADgIAAIgQgBgAECA3IgQgDQAAgJgDgNIATAEIAQACIAMgBIAJgDIAGgEQACgDAAgDQAAAAAAgBQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAIgGgCIgIAAQgHAAgHABQgGACgGADQgGACgCAEIgWgHIAIgRQAGgLACgJIgWgBIgBABIAAgWIALACIARABIADgUIAYACIgEARIAfgCQALgBAGgCIABAWIgJABIgtADIgIASIANgDIAQgBQAJAAAHABQAGACAGABQAFAEADAGQACAGAAAGIAAAIIgDAHIgFAFIgFAFIgIAEIgJADQgNADgIAAQgJAAgIgCgAgxAHIABgXIAEgcIACgLIAAAAIAYABIgEANIgFAZQgBAMAAAMIAKADQgDAJgBAJQgCAJAAANIABAFIgWABgAkQA2IgHgDIgGgEIgEgGIgDgHQgCgFgBgQIACg6IgBgKIAZABIgCAbIgBAjIABAOQAAAEACADQACADAEABQAEACAFAAIAKgBQAEgCAEgDQAEgDACgEIAFgJQADgHACgPIAMAJIALADIgIAXQgFAKgEAEIgIAHQgFAEgFACIgKADIgNABQgMgBgFgCgAAAA2QgEgBgEgDQgEgEgCgEQgCgFAAgFQAAgGACgFQADgFAFgDQADgDADgBQAFgCAHAAIAHABIAAgIIgBgLIgHAAIgZgBIAAgVQAGACARABIAJgBIAAgRIgBgHIAXAAIgBAXQAMgCAJgCIAAAUIgFABIgQADIABAZQAJAEAMAIIADACIgJAWIgGgGIgJgHIAAACQAAAEgCADQgCADgEADQgDACgFACQgGABgGAAQgHAAgFgCgAAFAbQgDACAAADQAAAAAAABQAAABAAAAQABAAAAABQABAAAAABQADABAEAAQAEAAACgCQADgBAAgEIAAgDIgIgBQgFAAgCABgAB+A1IgOgEIgIgEQgDgCgCgDQgDgDgBgEIgBgIIABgIIAEgIIAGgHIAIgGIAQAKQgFAEgDAEQgDAEAAAEQAAAAAAABQAAABAAAAQAAABABAAQAAAAAAABQACACADABIAJACIANAAIAYgBQAHgBALgEIACAZIgNACIggACIgTgBgAm+ANIgIABIAAgOIAIAAIAkAAIAAAOgAmigDIgkAAIAAgOIAsAAIAAAOgACCgSIAOgJIACgBIgLABIgdgCIgFAAIACgWIASACIAZABIAWgBIAOgBIABAUIgRAJIgUAOgAmjgWIgnABIAAgSIALABIAmgBIAAASIgKgBgAGRgfIgZgJIAKgTIALAFIAQAEQAOAEAMACIgHAVIgfgIgAnGgqIAAgPIAMAAIAUAAIAMAAIAAAPg");
	this.shape.setTransform(0,25.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(13));

	// Layer 4
	this.instance = new lib.btnbg();
	this.instance.setTransform(0,25.5,1,1,0,0,0,130,25.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},6).to({alpha:0},6).wait(1));

	// Layer 3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FC9E09").s().p("A0SAPIAAgdMAolAAAIAAAdg");
	this.shape_1.setTransform(0,49.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(13));

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FCCD2A").s().p("A0SDvIAAneMAolAAAIAAHeg");
	this.shape_2.setTransform(0,24);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(13));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-130,0,260,51);


(lib.bg2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_27 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(27).call(this.frame_27).wait(1));

	// Layer 2
	this.instance = new lib.bg2b();
	this.instance.setTransform(187.5,125,1,1,0,0,0,187.5,125);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(16).to({_off:false},0).to({alpha:1},11).wait(1));

	// Layer 1
	this.instance_1 = new lib.bg2a();
	this.instance_1.setTransform(187.5,125,1,1,0,0,0,187.5,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(28));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,375,250);


// stage content:
(lib.HighLow_300x250_4b_JA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		stage.enableMouseOver(20);
		
		this.loopNumber = 0 ;
		
		// CLICKTHROUGH
		this.clickTagBtn.addEventListener("click", function () {
			console.log("clickthrough");
			window.open(window.clickTAG);
		});
		
		// CTA
		this.clickTagBtn.addEventListener("mouseover", function () {
			exportRoot.bt.gotoAndPlay("on");
		});
		
		this.clickTagBtn.addEventListener("mouseout", function () {
			exportRoot.bt.gotoAndPlay("off");
		});
	}
	this.frame_243 = function() {
		if(this.loopNumber >= 1){
			console.log("STOP BANNER");
			this.stop();
		} else {
			this.loopNumber++;
			console.log("RESTART: " + this.loopNumber);
		}
	}
	this.frame_251 = function() {
		this.gotoAndPlay(1);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(243).call(this.frame_243).wait(8).call(this.frame_251).wait(1));

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A3bTiMAAAgnDMAu2AAAMAAAAnDgA3RTYMAuiAAAMAAAgmvMguiAAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(252));

	// clickTagBtn
	this.clickTagBtn = new lib._clicktag();
	new cjs.ButtonHelper(this.clickTagBtn, 0, 1, 2, false, new lib._clicktag(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickTagBtn).wait(252));

	// btn
	this.bt = new lib.btn();
	this.bt.setTransform(150,261);
	this.bt.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.bt).wait(191).to({y:181},0).to({alpha:1},7).wait(46).to({y:331},7,cjs.Ease.get(0.9)).wait(1));

	// t5
	this.instance = new lib.t5b();
	this.instance.setTransform(150,123.4,1,1,0,0,0,0,28.4);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(158).to({_off:false},0).to({alpha:1},7).wait(79).to({y:-96.6},7,cjs.Ease.get(0.9)).wait(1));

	// t5
	this.instance_1 = new lib.t5();
	this.instance_1.setTransform(245,122.1,1,1,0,0,0,95,25.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(153).to({_off:false},0).to({alpha:1},7).wait(84).to({y:-97.9},7,cjs.Ease.get(0.9)).wait(1));

	// logo
	this.instance_2 = new lib.logo_mc();
	this.instance_2.setTransform(148.5,57.8,1,1,0,0,0,64.5,18.8);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(191).to({_off:false},0).to({alpha:1},7).wait(46).to({y:-162.2},7,cjs.Ease.get(0.9)).wait(1));

	// strip
	this.instance_3 = new lib.strip();
	this.instance_3.setTransform(-5,125,1,1,0,0,0,3,125);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(4).to({_off:false},0).to({x:3},5,cjs.Ease.get(0.9)).wait(122).to({x:153},4,cjs.Ease.get(-1)).to({x:303},4,cjs.Ease.get(1)).to({_off:true},1).wait(104).to({_off:false},0).to({x:-3},7,cjs.Ease.get(0.9)).wait(1));

	// t3
	this.instance_4 = new lib.t3();
	this.instance_4.setTransform(-149.2,125.8,1,1,0,0,0,78.8,94.8);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(85).to({_off:false},0).to({x:120.8},7,cjs.Ease.get(1)).wait(39).to({x:270.8},4,cjs.Ease.get(-1)).to({x:420.8},4,cjs.Ease.get(1)).to({_off:true},1).wait(112));

	// t2
	this.instance_5 = new lib.t2();
	this.instance_5.setTransform(-120.5,124.5,1,1,0,0,0,87.5,77.5);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(39).to({_off:false},0).to({x:129.5},7,cjs.Ease.get(1)).wait(37).to({x:429.5},7,cjs.Ease.get(-1)).to({_off:true},1).wait(161));

	// t1
	this.instance_6 = new lib.t1();
	this.instance_6.setTransform(-145.6,124.5,1,1,0,0,0,92.4,77.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({x:134.4},7,cjs.Ease.get(1)).wait(30).to({x:484.4},7,cjs.Ease.get(-1)).to({_off:true},1).wait(207));

	// bg1
	this.instance_7 = new lib.bg1_1();
	this.instance_7.setTransform(150.5,125,1,1,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(131).to({x:300.5},4,cjs.Ease.get(-1)).to({x:450.5},4,cjs.Ease.get(1)).to({_off:true},1).wait(104).to({_off:false,x:455.5},0).to({x:150},7,cjs.Ease.get(0.9)).wait(1));

	// Layer 26
	this.instance_8 = new lib.bg2_1();
	this.instance_8.setTransform(-112.5,125,1,1,0,0,0,187.5,125);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(131).to({_off:false},0).to({x:37.5},4,cjs.Ease.get(-1)).to({x:187.5},4,cjs.Ease.get(1)).to({x:112.5},105).to({x:-187.5},7,cjs.Ease.get(0.9)).wait(1));

	// bg
	this.instance_9 = new lib._bg();
	this.instance_9.setTransform(150,125,1,1,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(252));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-85.6,125,536.1,312);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;